### ISSUE TITLE
Conversion issue when using List of generic types

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-stream#1098]
Found here: https://stackoverflow.com/questions/46672123/spring-cloud-dataflow-getting-payload-as-listmap

This does not impact 2.0 branch

On 1.x when someone sends a List<Map<K,V>> as json for example, on our inbound stream listener method invoker the `StringToCollection` conversion service is taking precedence over Jackson and it then converts the string : `[{"key":"val"}, {"key","val"}]` to a List of size 2 instead of a List of size 1  having a map with 2 entries.

Since we changed 2.0 for payloads to byte[] and we removed the `DefaultDatatypeChannelMessageConverter` from the converter list. This does not happen anymore.

A fix for 1.3.1 should be considered since this can lead to very odd stream behaviors when using json and lists

**Comment by olegz** [comment]
We may have fixed it already (at least partially). @garyrussell made a change here 1211a273f61a8de12b37b5c8bf4731a22ed023ed, so need to revisit

**Comment by olegz** [comment]
So, the issue is a bit tricky
For `@StreamListener` all we need to do is remove those additional argument resolves added from _ARGUMENT_RESOLVERS_BEAN_NAME_ (see BindingServiceConfiguration:109)
However for `@ServiceActivator` without doing something clever we end up with the issue described here https://jira.spring.io/browse/INT-4410
So there is a bit of inconsistency. . . stay tuned

**Comment by olegz** [comment]
Had a discussion with @artembilan and @garyrussell We all seem to agree that there is a minor bug in SI which is being addressed. Once it is this issue will essentially fix itself given the `ApplicationJsonMessageMarshallingConverter`'s functionality
