### ISSUE TITLE
BindingServiceProperties broken in actuator endpoint

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#1136]
```
"spring.cloud.stream-org.springframework.cloud.stream.config.BindingServiceProperties": {
"prefix": "spring.cloud.stream",
"properties": {
"error": "Cannot serialize 'spring.cloud.stream'"
}
}
```

**Comment by olegz** [comment]
@dsyer I tried many different things including using the [configuration](https://github.com/spring-cloud/spring-cloud-stream/issues/1124) that have apparently triggered this issue, but can not seem to reproduce it. Here is what I see:
<img width="742" alt="screen shot 2017-11-15 at 8 34 16 am" src="https://user-images.githubusercontent.com/172397/32838713-e536a2d6-c9df-11e7-9402-2fab8df86695.png">

**Comment by dsyer** [comment]
I still see that error in the project you linked to. Debugging shows me this:

```
java.lang.IllegalArgumentException: java.lang.Integer cannot be cast to java.lang.String (through reference chain: org.springframework.cloud.stream.config.BindingServiceProperties["binders"]->java.util.HashMap["rabbit-B"]->org.springframework.cloud.stream.config.BinderProperties["environment"]->java.util.Properties["spring.rabbitmq.connection-timeout"])
```

**Comment by olegz** [comment]
I see, let me try to figure it out

**Comment by olegz** [comment]
@dsyer I still can't reproduce it under normal circumstances. Basically the only way I can reproduce it is by injecting one of the properties as `'integer` by explicitly calling `put(object, object)` instead of `setProperty(string, string)`.  So, what may be setting this property as integer (calling that other method on property object?). I mean I don't think this is something we do in SCSt.  

Also. . .
I was able to track it down to jackson which picks `StringSerializer` for `Property` values. We can probably change `BinderProperties.environment()` to be a Map and force a more specialized serializer, but I am still curious as to who/what is setting it as integer. I mean there is some level of misscommunication with cloud-config I suspect that needs to be addressed, so I don't want to lose that either.

**Comment by dsyer** [comment]
I'm not sure, but I think it's just Spring Boot setting it to an Integer. The YAML has a Integer value. You have to switch the config server off or take it out of the equation somehow to see this behaviour because it is probably sending a String.

**Comment by olegz** [comment]
Yeah, this is actually a bit of a bigger issue then just serialization. While implying `String/String`, the `Properties` class doesn't enforce it (neither for Key nor Value), but since Jackson treats it as `String/String` you can see the discrepancy where you can easily set anything you want and Jackson will automatically be casting it to `String`. 

However, the bigger issue is that `BinderProperties` assumes simple properties definition while delegating to the Binder's implementation what that may be, and that may very well be a hierarchy where the value of a property may itself be a `Map` of key/values.

Anyway, I'm changing it to `Map<String, Object>`. Technically this is a breaking change which we should document in the upgrade/migration guide, but IMHO it is also a bug that needs to be fixed.
