### ISSUE TITLE
Multiple StreamListeners using Thread (Inside a single VM)

### ISSUE THREAD

**Issue by sivasyams** [spring-cloud/spring-cloud-stream#1154]
Hi,

I have a scenario in which i want to have multiple @StreamListener listening on different topics and reading parallely. I have redefined the Sink interface and was able to implement multiple @StreamListener on different topics. But what i wanted is some other case.

I want like to implement multiple @StreamListener listening of different topics parallely, using a threaded mechanism inside a single java VM. 

Is there any possibility for this case? 

Thanks

**Comment by olegz** [comment]
@sivasyams You don't need to do anything since the thread-based message dispatching mechanisms resides with the binder itself in a form of task executor which essentially dispatches messages to message handlers identified by one of the handler annotations (i.e., `@StreanListener`).

**Comment by sivasyams** [comment]
Hi,

I think my scenario was not clear to you. I want to spawn the @StreamListener at run time as different threads based on certain criteria and shut it down as well after some time. So, what i am asking is, if there is a possibility to run these listeners as worker threads under a thread pool.

**Comment by olegz** [comment]
I am still not sure I understand what you're trying to accomplish. 
The listeners are invoked by the thread pool managed by the binder's `MessageListenerContainer`'s _concurrency_ setting. 
What I am suspecting is that you may be talking about ability to process certain messages in parallel  while others serially (based on some criteria). Is that the case?

**Comment by olegz** [comment]
Just to add. . . I'd suggest if you can explain your use case rather then discuss the proposed solution which may actually be wrong to begin with.

**Comment by sivasyams** [comment]
I am asking about the ability to process messages from multiple topics in parallel using seperate @StreamListener for each topic. 

I want it in a way that, rather than creating the required number of @StreamListeners before the starting the program, is there a way to create those listeners during runtime?

**Comment by olegz** [comment]
Unfortunately, you are still describing a solution instead of the problem. 
Sure you can add/remove a listener by starting another instance of your microservice application (which would be the equivalent of creating another listener) and binding to the same destination. But you could do the same much more efficiently with a single instance by simply increasing the amount of concurrent consumer. . . etc.

As I suggested, there may be other reasons driven by some edge-case functional requirements, but you need to describe what they are so we can jointly come up with the appropriate solution. 

Please don't take it the wrong way. We are truly trying to help, but we need to work together to get there.
