### ISSUE TITLE
Is threre a solution to bolck a partition consumer

### ISSUE THREAD

**Issue by jonwinters** [spring-cloud/spring-cloud-stream#1156]
In my project, I found if partitionCount equals consumer concurrence，
one thread consume one partition (I thought partition is FIFO queue),

In a particular moment , I want to block other thread (not to consume message  from partition) until specific thread consume one specific message

in code 
```
@StreamListener(target = Input0.INPUT)
@Transactional(rollbackFor = Exception.class)
public void handleMessage(Message<StoredEvent> msg) throws IOException {
        while(condition != true){
             Thread.sleep(2000);
              if ( checkCondition()){
                   condition == true;
               }
        }
        consumerPersonCreateEvent(msg);
}
```

how to implement that ？

**Comment by artembilan** [comment]
GitHub is not the place for questions. We might just not be available to answer. In the public community forum (e.g. StackOverflow) you can get a help from any member.

You problem isn't clear, but since you are asking about particular solution, Spring Integration provides one for you - `BarrierMessageHandler`: https://docs.spring.io/spring-integration/docs/5.0.0.RELEASE/reference/html/messaging-routing-chapter.html#barrier

**Comment by jonwinters** [comment]
@artembilan  thanks
