### ISSUE TITLE
Add support for ExecutorSubscribableChannel in @Input and @StreamListener

### ISSUE THREAD

**Issue by lchayoun** [spring-cloud/spring-cloud-stream#1173]
Spring Cloud Sleuth is using TraceChannelInterceptor in order to continue the spans through the messaging system.
TraceChannelInterceptor is using the ExecutorChannelInterceptor#beforeHandle method.
If the channel is not an ExecutorSubscribableChannel tracing is not possible along with other capabilities regarding the parsing of incoming messages headers.

**Comment by olegz** [comment]
@lchayoun Could you please raise this question with Spring Cloud Sleuth as it appears it's an issue with Sleuth, but regardless we can work together.
Tagging @marcingrzejszczak

**Comment by lchayoun** [comment]
@olegz I don't think it is an issue with Sleuth.
Currently the only way to handle messages before the method annotated with "@StreamListener" is called is on `PollableChannels` with the "postReceive" method.
When using `SubscribableChannel` this is possible only using the `ExecutorChannelInterceptor#beforeHandle` method.
But `ExecutorSubscribableChannel` is not supported by the "@Input" annotation factory,

**Comment by artembilan** [comment]
@lchayoun,

let us know, please, why `preSend()` phase is not OK for you here?

The problem is really that `TraceChannelInterceptor` should be able to work with any `MessageChannel` implementation which accepts interceptors. So, that is really already outside of SCSt and belongs to SC Sleuth.

Thank you!

**Comment by olegz** [comment]
I am still not convinced since adding interceptors is defined on _AbstractMessageChannel_. 
Keep in mind that adding interceptors is typically accomplished outside of Spring Cloud Stream (SCSt), so if there is a disconnect somewhere I doubt it is in SCSt. So I am curious as to what @marcingrzejszczak has to offer.

**Comment by lchayoun** [comment]
both `preSend()` and `beforeHandle()` are used, the first to put the span header and the other to build the span from the header:

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java#L99

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java#L172

I think that `org.springframework.integration.channel.ExecutorChannel` will also work

**Comment by artembilan** [comment]
@olegz , 

looks like that `TraceChannelInterceptor` has been designed after `org.springframework.messaging.support.ExecutorSubscribableChannel` and seems like no body cared that there is Spring Integration with its `AbstractMessageChannel`.

@lchayoun ,

I see. So, I think that the flaw is really in the `TraceChannelInterceptor` such as it doesn't support non-`ExecutorSubscribableChannel`. I'm really surprised to hear that since this interceptor is there for a while already 😄 

Let's really move discussion to that SC Sleuth issue from here. Really nothing to do on SCSt side.

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/572 will sort this out fyi

**Comment by olegz** [comment]
Thanks @adriancole If there is a related issue in sleuth/zipkin etc, please link it to this issue if you don't mind

**Comment by olegz** [comment]
@lchayoun out of curiosity, how do you create custom channels? I mean what the mechanism you're using? Do you provide your own implementation of `BindingTargetFactory`? Also, what is your reason for customizing binding target channels?

**Comment by lchayoun** [comment]
I customized it using `AbstractBindingTargetFactory`:
```java
import org.springframework.cloud.stream.binding.AbstractBindingTargetFactory;
import org.springframework.cloud.stream.binding.CompositeMessageChannelConfigurer;
import org.springframework.context.annotation.Primary;
import org.springframework.integration.channel.ExecutorChannel;
import org.springframework.stereotype.Service;

@Primary
@Service
public class ExecutorChannelBindingTargetFactory extends AbstractBindingTargetFactory<ExecutorChannel> {

    private final CompositeMessageChannelConfigurer compositeMessageChannelConfigurer;

    public ExecutorChannelBindingTargetFactory(CompositeMessageChannelConfigurer compositeMessageChannelConfigurer) {
        super(ExecutorChannel.class);
        this.compositeMessageChannelConfigurer = compositeMessageChannelConfigurer;
    }

    @Override
    public ExecutorChannel createInput(String name) {
        ExecutorChannel executorChannel = new ExecutorChannel(Runnable::run);
        this.compositeMessageChannelConfigurer.configureInputChannel(executorChannel, name);
        return executorChannel;
    }

    @Override
    public ExecutorChannel createOutput(String name) {
        ExecutorChannel executorChannel = new ExecutorChannel(Runnable::run);
        this.compositeMessageChannelConfigurer.configureOutputChannel(executorChannel, name);
        return executorChannel;
    }
}
```

This is the only way I found to make it work.
I'll be glad to remove this code and use spring-cloud-stream implementation

**Comment by olegz** [comment]
Thank you so much @lchayoun for following up. That really clears it up. We'll let you know once this can be removed. Tagging @adriancole @marcingrzejszczak
