### ISSUE TITLE
KStreamListenerParameterAdapter crashes with NPE on Kafka tombstones records

### ISSUE THREAD

**Issue by rliwoch** [spring-cloud/spring-cloud-stream#1199]
Recently I've been working with a Kafka Connect connector (Debezium Mongo) which by default is utilising the Kafka topic compaction, it was not a desired behaviour for my use case so I've submitted a PR to their repository (worth checking as it will show how I got to the error I'm about to describe https://github.com/debezium/debezium/pull/421)  

The problem is that `KStreamListenerParameterAdapter` will not handle kafka `tombstones` records properly and it will crash with `NullPointerException` when it tries to consume a kafka message which is a `tombstone`.
```
		return bindingTarget.map(new KeyValueMapper() {
			@Override
			public Object apply(Object o, Object o2) {
				if (valueClass.isAssignableFrom(o2.getClass())) {
					return new KeyValue<>(o, o2);
				}
```
the `o2.getClass()` will generate `NPE`

Here is the snapshot from the topic, first message is a delete operation, the second one is the tombstone `null` associated (and generated) with this delete message.
![1-1](https://user-images.githubusercontent.com/26857299/35572381-6a5b8a58-05cc-11e8-81f9-3af8b3e36f47.png)

And here's where the explosion is about to happen:
![2](https://user-images.githubusercontent.com/26857299/35572418-79f01786-05cc-11e8-9b4c-875c742a0c5e.png)

Detected in:
package: `org.springframework.cloud.stream.binder.kstream`
class: `KStreamListenerParameterAdapter`
maven co-ords to the jar: `org.springframework.cloud:spring-cloud-stream-binder-kstream11:1.3.0.RELEASE`

**Comment by sobychacko** [comment]
@rliwoch Thanks for reporting this. It looks like this is a bug. We will filter out null values in the adapter as you cannot do any stream processing on that anyway.  Will try to fix it in the 2.0 timeline. Any further feedback or better yet contributions are welcomed! Thank you.

**Comment by garyrussell** [comment]
@sobychacko Spring Kafka has a special message payload type `KafkaNull` for tombstone messages.

When we invoke the `@KafkaListener` we coerce the `KafkaNull` payload to `null`; the user has to set `@Payload(required = false)` on the method argument ([doco here](https://docs.spring.io/spring-kafka/reference/html/_reference.html#_log_compaction)).

User code, therefore, does not have to know about the special payload on the receiving side. When using Spring Integration Kafka (outbound), sending a message with a `KafkaNull` payload is sent as a tombstone record.

It's important to process tombstone messages because it signals the removal of a key from a compacted topic.

I don't know how this relates to Kafka Streams and whether they should support tombstones but I thought I should give you some background.

**Comment by rliwoch** [comment]
I hope you won't mind adding my opinion.
I would even tackle it from a different angle and said that there should be a level of customization allowed with regards to handling tombstones in streams. Log compaction isn't instantaneous, but I can think of a scenario in which a streaming app is consuming  the compacted topic and sends it downstream. If the upstream application uses only tombstones for certain actions then the processing kafka streams application would need to know that some messages which have already been read, processed and emitted to another topic/sink need to be "cancelled".

Example:
A web application emits messages to userActions topic for every user action on the website, but when the user logs out it would emit a tombstone only for a given key, say, session id. There is a kafka streams application consuming userActions topic and processes messages, some of them are branched to other topics, same of them sink to database. If the tombstone will get arbitrarily rejected(dropped) then processing application wouldn't be able tell the session has ended (and pass the information further) .
On the other hand, I made up this scenario, and in fairness I would expect such web app to emit sessionTerminated record and then perhaps a tombstone (as the mentioned  debezium connector  does by default).

**Comment by sobychacko** [comment]
@garyrussell Thank you for that information. @rliwoch we don't mind feedback at all!. I think using what @garyrussell suggested with `@Payload` annotation, we might be able to support not dropping the tombstones arbitrarily, but handle them so that the NPE is avoided and the user code can appropriately make application-level decisions. However, this needs to be a bit more thought out because at the moment, the binding only supports `KStream<?,?>` as the inbound type. We need to allow arbitrary types with `@Payload` but somehow maps the incoming `KStream` to the payload type. It is not as straightforward as simply dropping the tombstone record and not allowing that to be processed. We will see if we can mitigate a common ground to address this.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#294
