### ISSUE TITLE
Support for reactive webapps with `AggregateApplicationBuilder`

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#1214]
I guess it still makes sense to support a boolean flag here for `webEnvironment`, but the fact that it depends on being a servlet app is  a legacy feature that ought to be smoothed out now that reactive web apps are also a thing in Spring Boot.

Also, using `Class.forName()` is ugly and should probably be replaced by `ClassUtils.isPresent()`.

**Comment by olegz** [comment]
@dsyer I am considering deprecating 'AggregateApplicationBuilder' all together since I believe there is a better/simpler way to achieve what it does, so I am reluctant to spend any more time on trying to improve it. 
As for `Class.forName()` vs `ClassUtils.isPresent()`, i'll fix that. Forgot about it.
