### ISSUE TITLE
Can't instrument channels created via BinderAwareChannelResolver

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-stream#1219]
when resolving a message channel dynamically there seems to be no option to hook in a channel interceptor. In case of Sleuth it's called `TraceChannelInterceptor`. Due to missing channel interceptor a message is not instrumented and trace is not continued.

Affected Cloud BOM versions: `Edgware`, `Finchley`
Sample project: https://github.com/marcingrzejszczak/trace-id-issue-reproducer/tree/edgware_2
Related issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/821

**Comment by artembilan** [comment]
@marcingrzejszczak ,

As a workaround I suggest you to consider to implement `BeanPostProcessor` and add interceptor there from there `postProcessBeforeInitialization()`. You should ensure do not use any injection for such a bean because of "early BeanFactory access syndrom", but postpone the `TraceChannelInterceptor` extraction from the context to the `afterSingletonsInstantiated()` and only when the `interceptor` property is not `null` allow to add it into the `MessageChannel` beans. This way you won't instrument channel beans during init phase since that is done by the `@GlobalChannelInterceptor`. Essentially your `BPP` will be like companion artifact to the `@GlobalChannelInterceptor`. This one is for init phase, but your is for runtime. That's why I suggested you to take a look to the hook which can be called from the `this.beanFactory.initializeBean(channel, channelName);`.

BTW that is exactly what I'm going to do on the Spring Integration side: https://jira.spring.io/browse/INT-4402

But as you see that is going to happen only the next `5.1` version.

This issue, @olegz , in the SCSt, is about autowiring the `MessageChannelConfigurer` beans declared by the end-user to the `CompositeMessageChannelConfigurer`.

**Comment by olegz** [comment]
Yeah, no need for workaround. I already targeted it for RC1, so it will be fixed

**Comment by marcingrzejszczak** [comment]
I'll need to create a workaround for Edgware.

**Comment by marcingrzejszczak** [comment]
BTW do I understand correctly that this will fix the `BinderAwareChannelResolver` issue *AND* this issue https://github.com/spring-cloud/spring-cloud-sleuth/issues/821 ? So the when the channel is marked with `@input` ?

**Comment by artembilan** [comment]
@marcingrzejszczak ,

See my comment in that issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/821#issuecomment-355567825

One more time:

The `TraceChannelInterceptor` doesn't support `AbstractMessageChannel` from Spring Integration. 

That's all what we should know for that issue.

It isn't related to this one though, but we will get a gain there on the instrumenting side for the dynamic destination as well.

**Comment by marcingrzejszczak** [comment]
Ok, thanks for the reminder, now I seem to remember everything. Thanks a lot.
