### ISSUE TITLE
[QUESTION] JSON support

### ISSUE THREAD

**Issue by dodalovic** [spring-cloud/spring-cloud-stream#1236]
Hi, guys, one quick question:
How do I write application that produces message to some kafka topic, and at the same time listens at the same topic (using `@StreamListener`), with messages being serialized as **JSON**, something like:

... Producer part

```java
...
source.send(MessageBuilder.withPayload(new MySamplePojo()).build());
```

... Consumer part

```java
@StreamListener(Sink.INPUT)
public void processMySamplePojo(MySamplePojo pojo) {
...
```

Thanks so much for all the effort!

**Comment by olegz** [comment]
I am a bit confused about your use case since I am not sure I fully understand why do you need to bring Kafka in between. And if you do, then you are essentially creating `Source -> Sink` and it is better to have Source and Sink as separate apps as it allows for independent lifecycle management (consumer(Sink) can be down while producer(Source) is up and running)

**Comment by dodalovic** [comment]
I have fixed requirement to provide application that puts message on the topic as JSON string, and reads the same topic and processes that message.

**Comment by olegz** [comment]
I am not following. We're not talking about JSON at the moment. In fact framework supports sending/receiving POJOs and conversion to/from will happen transparently, but that is not what I am asking.  Please read my question. There is an architectural issue that I am trying to understand

**Comment by dodalovic** [comment]
There can be requirement that for incoming web request we just need to put message to kafka and then process it asynchronously by reading from the same topic. Furthermore it may be that there's a requirement to accomplish this with one process.

**Comment by dodalovic** [comment]
If this is not possible, it would be nice to just find out how to send pojo to kafka topic as json string and read the same pojo unmarshalled using @StreamListener annotation

**Comment by olegz** [comment]
Generally, Spring Cloud Stream allows one to write application (microservices) in a transparent way from the actual middleware it binds to, so your application code will look the same regardless of the binder you are using (i.e., Kafka, Rabbit etc). So if you wan to interact directly with Kafka, you may very well want to use https://github.com/spring-projects/spring-kafka. 
You can also try to define custom binding interface and bind your `@Input/@Output` destination to the existing topic using binding configurations.

That said, I am still not following; You're saying _. . .put message to kafka and then process it asynchronously. . ._ That is absolutely fine requirement and is accomplished as two independent microservices stereotyped as `Source` and `Sink` connected with Messaging middleware such as Kafka. Otherwise what you're building could arguably NOT qualify as microservice but rather a conventional application and is better handled by general purpose frameworks. As for _...may be that there's a requirement to accomplish this with one process..._ is not a requirement, rather opinion which I am questioning. 

Don't get me wrong, but also understand that SCSt is not a general purpose framework like Spring-Kafka or Spring-Integration. It is specialized framework to build message driven microservices - _services that are connected with one another with messaging middleware_.

As for String representation of JSON or POJO as I mentioned before framework transparently handles message conversion so whether you want POJO or String representation of it as JSON it is handled transperently

**Comment by sobychacko** [comment]
@dodalovic have you tried this? It should be possible to do what you are asking out of the box. You are basically serializing a message into JSON and send to kafka. On the consuming side, you are trying to receive it as a POJO, as your `StreamListener` example shows above. This is a basic use case supported out of the box as @olegz alluded to above. If it doesn't work, tell exactly where it is not working. Thanks!

**Comment by olegz** [comment]
Also, as a good practice, these type of questions are better be asked in Stack Overflow (https://stackoverflow.com/questions/tagged/spring-cloud-stream)

**Comment by dodalovic** [comment]
@olegz Thanks for the lecture about architecture. @sobychacko Thanks for the link actually, nice to know for the tag ;)
