### ISSUE TITLE
test-support should support content-type property

### ISSUE THREAD

**Issue by jkubrynski** [spring-cloud/spring-cloud-stream#1237]
Currently, without setting `content-type` property on the binder, tests are still working correctly. At the same time, the production implementation uses binary encoding, which leads to serious production issues (due to for example encoding enums with ordinal, etc).

Also the question is why we need to configure `content-type` on the binder, while the same setting is passed on message headers.

**Comment by olegz** [comment]
@jkubrynski sorry to hear you're experiencing issues. I am assuming you're using 1.3.x version of SCSt where I'll admit we had some inconsistencies with content-type negotiations. 
It has already been fixed in the current master (2.x) with release coming in the next month or so (we're aiming for RC1 this Friday).
You are correct (if I understand you correctly), the content-type coming with Message header should take precedence over binding content-type and that is part of many content-type negotiations improvements that went into 2.0. So please give it a shot if you can.

**Comment by jkubrynski** [comment]
I've tried Boot `2.0.0.RC2` with `Finchley.M6` but it ends up with:
```
Failed to instantiate [org.springframework.cloud.context.properties.ConfigurationPropertiesBeans]: 
Factory method 'configurationPropertiesBeans' threw exception; nested exception is 
java.lang.NoSuchFieldError: BINDER_BEAN_NAME
```

**Comment by olegz** [comment]
@jkubrynski can you please switch to Finchley.SNAPSHOT? It appears to be a known issue. I believe Finchley.M7 is coming shortly

**Comment by jkubrynski** [comment]
It looks like it works correctly with 2.0.0. Thanks @olegz !
