### ISSUE TITLE
JaaS Keytab Property value issue 

### ISSUE THREAD

**Issue by sundarsrini** [spring-cloud/spring-cloud-stream#1238]
Hi,

We have a kafka server running with kerberos authentication. So in order to provide authentication the below property is used. 

**application.properties:**
spring.cloud.stream.kafka.binder.configuration.ssl.truststore.location=server.truststore.jks
spring.cloud.stream.kafka.binder.configuration.ssl.keystore.location=server.keystore.jks
spring.cloud.stream.kafka.binder.jaas.options.keyTab=event_framework.keytab

We have placed the above files in src/main/resources directory. 

I am not sure if the resource locator is implemented as a part of this config, because when we build a jar then application is unable to read the file location though the files are present inside classes directory. 

**Information for your reference:** 
<spring-cloud.version>Edgware.RELEASE</spring-cloud.version>
spring-cloud-stream-binder-kafka - 1.3.0 
spring-cloud-starter-stream-kafka - 1.3.0

Can anyone please help! 

Thanks
Sundar

**Comment by olegz** [comment]
@sundarsrini When you say _application is unable to read the file location_ do you have any stack trace to show the actual error you're getting or is it just an assumption? Have you actually looked inside the JAR (unzip it) and see that the file is there?

**Comment by artembilan** [comment]
Correct. It's not implemented for those `options`. Just because they all are delegated to the JAAS as is:
```
AppConfigurationEntry kafkaClientConfigurationEntry = new AppConfigurationEntry
						(binderConfigurationProperties.getJaas().getLoginModule(),
								binderConfigurationProperties.getJaas().getControlFlagValue(),
								binderConfigurationProperties.getJaas().getOptions() != null ?
										binderConfigurationProperties.getJaas().getOptions() :
										Collections.<String, Object>emptyMap());
```
That's how JAAS works. Not a Spring Cloud Stream issue.

See here for more information: https://henning.kropponline.de/2016/02/21/secure-kafka-java-producer-with-kerberos/

Pay attention how they talk about the `keyTab` file:
>  Before we can do this we need to create the keytab storing it also under /home/kafka-user/kafka-user.keytab.

and then a bit below:
```
KafkaClient {
 com.sun.security.auth.module.Krb5LoginModule required
 doNotPrompt=true
 useTicketCache=true
 principal="kafka-user@MYCORP.NET"
 useKeyTab=true
 keyTab="/home/kafka-user/kafka-user.keytab"
 client=true;
};
```

Do you see how JAAS just relies on the full absolute file path?

That's the same only what you can do here as well.

I'm afraid there is nothing what we can do on the matter.

More over I think it is counterproductive and very unsecure to store key & trust and login files into jar directly. They really must be stored somewhere in the target operation system (or external token) and used from these configuration options as full absolute file paths.

Does it make sense to you?

**Comment by sundarsrini** [comment]
It makes a lot of sense. 

Agree that its not spring cloud stream issue. But there will be issues while deploying the application to PCF platform where I cant place the files in the target system. 

Can you help know what you mean by external token ? 

Appreciate your help!

**Comment by sundarsrini** [comment]
@artembilan Thanks for the response. Totally agree with your suggestion.
