### ISSUE TITLE
Consider providing support for back-pressure management

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1262]
Earlier today @jkschneider and I had a brief discussion on this subject, so I wanted to capture some of the key points:

To support back-pressure we need to  have some type of mechanism where consumers can issue periodic notifications about their rate of consumption (polling or event driven). This way producers remain decoupled from the consumers yet they will become consumers of these notifications and act on it (i.e., change the rate of message production or stop/pause completely).
 
[Jon] The rate is always achievable from a plain counter. But micrometer makes the determination about whether we need to expose that rate directly (e.g. jmx, graphite, ganglia, atlas, influx, datadog) or the consumer should use their monitoring system’s rate function.

Also we need to make sure that this or any other mechanism will not couple producers and consumers (logically of physically). One way would be to have some time of `correlationId` so a producer can correlate these notifications without having any knowledge of the consumer and vice versa.

So this essentially becomes somewhat of a async circuit breaker

**Comment by mv78** [comment]
I did not see this and created similar request in SCDF project.

Currently, SCDF receives metrics from all apps via metrics service.
It would be good addition to have to dynamically scale up consumers to increase message processing throughput based on message rate of the queue/exchange its bound to or using consumer utilization rate for given queue.

I am thinking that spring cloud stream could provide mechanism for deployed consumers to receive its queue's consumer rate (i.e. rabbitmq management queue's consumer rate) and expose it as custom metrics. Than when k8s deployment is created, we can also add horizontal pod autoscaler spec to tie to that custom metrics so that consumer app would be autoscaled based on consumer rate for their respective queue.

**Comment by olegz** [comment]
This should be handled by the underlying binder API and at the moment we have non-reactive binder API. In other words we simply need to start developing reactive binders (e.g., RSocket, Reactive Kafka etc)
