### ISSUE TITLE
message conversion error with @Transformer but not with @ServiceActivator

### ISSUE THREAD

**Issue by altfatterz** [spring-cloud/spring-cloud-stream#1309]
I have a simple processor app transforming from message in XML format to a message in JSON format:

```yml
spring:
  cloud:
    stream:
      bindings:
        output:
          content-type: application/json
        input:
          content-type: application/xml
```

with the following transformer

```java
    @Transformer(inputChannel = Processor.INPUT, outputChannel = Processor.OUTPUT)
    public GreetingResponse transform(Greeting greeting) {
        logger.info("received greeting message" + greeting);
        GreetingResponse response = new GreetingResponse("Hallo " + greeting.getFrom());
        return response;
    }
```

```java
    @Bean
    @StreamMessageConverter
    public MessageConverter greetingConverter() {
        return new GreetingMessageConverter();
    }

    static class GreetingMessageConverter extends AbstractMessageConverter {

        private final ObjectMapper objectMapper;

        public GreetingMessageConverter() {
            super(MimeType.valueOf("application/xml"));
            objectMapper = new XmlMapper();
            objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        }

        @Override
        protected boolean supports(Class<?> clazz) {
            return clazz.equals(Greeting.class);
        }

        @Override
        protected Object convertFromInternal(Message<?> message, Class<?> targetClass, @Nullable Object conversionHint) {
            try {
                return objectMapper.readValue((byte[]) message.getPayload(), Greeting.class);
            } catch (IOException e) {
                return null;
            }
        }
    }

```

Receive the error:
```
Caused by: java.lang.IllegalStateException: Failed to convert message: 'GenericMessage [payload=com.example.springcloudstreamprocessorexample.GreetingResponse@20de05e5, headers={contentType=application/xml, id=dc752790-51a2-b8c6-aa8d-ef52c98d4192, timestamp=1521283966338}]' to outbound message.
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$OutboundContentTypeConvertingInterceptor.doPreSend(MessageConverterConfigurer.java:335)
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$AbstractContentTypeInterceptor.preSend(MessageConverterConfigurer.java:362)
	at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:611)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	... 47 more
```

It is interesting that if I use `@ServiceActivator` then I don't get message conversion error.
Here you can find the example code:
https://github.com/altfatterz/spring-cloud-stream-processor-example

Could you help me to understand why is not working with `@Transformer`

**Comment by olegz** [comment]
@altfatterz From a quick glance what you have should NOT work, so I am not sure what do you mean it does with ServiceActivator but not Transformer. The reason why it should not work is because your custom transformer only supports `Greeting` and what you're producing is `GreetingResponse`.

Meanwhile I'll look in a little bit and will post here

**Comment by olegz** [comment]
@altfatterz Actually all is good and your code is correct and it should work regardless of the annotation used. 
The problem you're experiencing is related to a known bug in Spring Integration where the inbound `contentType` header was propagated to the outbound message. That bug *only* exists for `@Transformer` - https://jira.spring.io/browse/INT-4397. So, until it is addressed please use `@ServiceActivator` since it is completely interchangeable.

Also, I noticed you are on RC2. Please upgrade to RC3 of Spring Cloud Stream if/when you gte a chance as it is the lates and hopefully the last RC.

Since we're on the topic of content type negotiations here are few relevant links that you may want to read (unless you already did)
[Reference Manual](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.BUILD-SNAPSHOT/reference/htmlsingle/#contenttypemanagement)
[Blog](https://spring.io/blog/2018/02/26/spring-cloud-stream-2-0-content-type-negotiation-and-transformation)

**Comment by altfatterz** [comment]
@olegz Thanks a lot.
