### ISSUE TITLE
Error: Multiple destinations cannot be specified

### ISSUE THREAD

**Issue by ennala** [spring-cloud/spring-cloud-stream#1526]
Hi,

I am trying to write output of a processor to two kafka output streams like following. I also see similar example like this in one of the sample examples.

`
@StreamListener(SampleBinding.INPUT1)
@SendTo({SampleBinding.OUTPUT1, SampleBinding.OUTPUT2})

public String handleM(String sampleMessage){
      log.info("Received message="+sampleMessage.toString());
      sampleMessage=sampleMessage.toUpperCase();
     return sampleMessage;
}
`

But its throwing me the following error. Its working fine with one output. 
Is multiple destination support removed from spring cloud streams ?

> java.lang.IllegalArgumentException: Multiple destinations cannot be specified at org.springframework.util.Assert.isTrue(Assert.java:118) at org.springframework.cloud.stream.binding.StreamListenerMethodUtils.getOutboundBindingTargetName(StreamListenerMethodUtils.java:146) at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor$DefaultStreamListenerSetupMethodOrchestrator.orchestrateStreamListenerSetupMethod(StreamListenerAnnotationBeanPostProcessor.java:349) at

**Comment by olegz** [comment]
This is indeed not supported nor there are any plans to support it, since what you are trying to do is typically delegated to messaging systems (JMS, AMQP etc), where multiple subscribers can subscribe to a single destination (i.e., topic). Your approach is essentially a message duplication.

Also, next time when you do have a question, please user [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-cloud-stream) or [Gitter](https://gitter.im/spring-cloud/spring-cloud-stream) for it. We use GitHub Issue tracking for filing the actual issues and the broader community is well aware of that, hence won't be looking for answers here.
