### ISSUE TITLE
StreamListener condition spel use beans in application context

### ISSUE THREAD

**Issue by nhomble** [spring-cloud/spring-cloud-stream#1550]
Has anyone considered allowing for users of stream listener to reference their own functional interfaces in their condition spel? Benefits I can imagine with this kind of support are:
- better reuse of common headers across consumers
-- because I can define custom headers as string constants and then reuse these across my impls
- debuggability
-- I find it convenient to be able to put break points at these evaluation points
So something like
```
@StreamListener(target = "my_channel", condition = "#{myChannelCondition.accepts(headers)}")
```
Where myChannelCondition is a qualified bean in my spring config. I find similar behavior in spring data mongo's ```@Document``` annotation when determining collection name. Further more, in the camunda's spring boot starter, workflow conditionals can also be delegated to beans in the context.

**Comment by olegz** [comment]
I am not particularly a fan of `condition` attribute on StreamListener . . . TL;DR, but I think given that we already have it as a feature, this could be helpful. 
We'll certainly consider it. . .
Also, if you interested in submitting a PR it may speed up the process

**Comment by olegz** [comment]
No huge problem, but to me architecturally it is a bit awkward, since it effectively merges router and service into a single component. 
I mean if you need to introduce routing and other EIP patterns within a single microservice you could just as well use pure Spring Integration(SI) inside of Spring Cloud Stream(SCSt) app and enjoy all the additional bells and whistles that comes with, including ability to reference AC beans in your SPEL. . . which now makes me think if we really want to implement this feature at all or simply recommend to use SI. Basically I do not want to end up partially re-creating and then maintaining code that is already implemented fully in the framework that is used at the core of SCSt...

**Comment by garyrussell** [comment]
Oleg's objections notwithstanding (I tend to agree with him, BTW), but this is already supported because the SPeL evaluation context has a bean resolver...

```java
@SpringBootApplication
@EnableBinding(Sink.class)
public class Sgh1550Application {

	public static void main(String[] args) {
		SpringApplication.run(Sgh1550Application.class, args);
	}

	@StreamListener(value = Sink.INPUT, condition = "@condition.test(headers)")
	public void listener(String in) {
		System.out.println(in);
	}

	@Bean
	public Predicate<Map<String, Object>> condition() {
		return m -> "bar".equals(m.get("foo"));
	}

}
```

**Comment by olegz** [comment]
Feel free to close this issue once you validate that Gary's suggestion works for you
