### ISSUE TITLE
Provide additional information on DefaultBinding 

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream#1556]
I am trying to subscribe to the `BindingCreatedEvent` emitted on new binding creation but feel the event could have some more relevant information on it.

1. Is it intentional for DefaultBinding to not expose the underlying target? 
2. Just like #1425, does it make sense for a binding to identify itself as inbound or outbound?

**Comment by olegz** [comment]
No it is not intentional. In fact could you share (as a user) what would you like to see in such event?
We can probably do this as a minor enhancement before 2.1.0 release.

**Comment by olegz** [comment]
I'll take that back. Yes it is intentional to not expose `target` to prevent any manipulation to it outside normal lifecycle operations. Also, the target is technically a `T`, which means it is up to a target to expose things which could lead to more potential for exposing dangerous operation unintentionally.
So the best way forward is to list things you want to be able to see and we can proxy them with relevant getters.

**Comment by Walliee** [comment]
So the two things that I'd be really interested in would be:

1. Indication whether newly created binding is inbound or outbound
2. Bean name of the target

**Comment by Walliee** [comment]
@olegz Did you get a chance to consider this?

**Comment by olegz** [comment]
Yes, sorry for not getting back to you earlier, but we'll address it 2.2  (perhaps 2.1.1) time frame. It's too late for 2.1.0 as we're about to cut the release

**Comment by Walliee** [comment]
Not a problem but do you think both of the asks are reasonable?

**Comment by olegz** [comment]
Yes, very reasonable. . .

**Comment by olegz** [comment]
I am about to push a minor enhancement for this. It turns out that the only thing that is missing as you pointed out is Input and/or Output. The name and the rest of the extended information is already available.
For example

```
    @Override
    public void onApplicationEvent(BindingCreatedEvent event) {
	Binding<?> source = (Binding<?>) event.getSource();
	System.out.println(source.getName());
	System.out.println(source.getExtendedInfo());
	System.out.println(source.isInput());
    }
```
From the above the only new operation is `isInput()`. The `name` attribute will return you the channel name and the `extendedInfo` will return a `Map<String, Object>` containing the additional information. 
The newly added `isInput()` is a simple binary check. If `true` it is, otherwise it is `output`.

Please raise raise a separate issue if you require some additional information
