### ISSUE TITLE
Vanilla Schema Registry Client doesn't work with autoconfigured Redis cache

### ISSUE THREAD

**Issue by dmarmugi** [spring-cloud/spring-cloud-stream#1566]
### Setup
Using a vanilla `SchemaRegistryServer`: 
```java
@SpringBootApplication(exclude = [SecurityAutoConfiguration.class])
@EnableSchemaRegistryServer
class SchemaRegistryServerApplication {
    static void main(String[] args) {
        SpringApplication.run SchemaRegistryServerApplication.class, args
    }
}
```
Sample app at github.com/dmarmugi/schemaregistryclient-redis-sample.git
- `master` branch has redis dependencies
~~- `caffeine` branch has caffeine dependencies~~

### What happens
adding cache provider(tested with redis ~~and caffeine~~) dependencies to a `SchemaRegistryClient` app causes ~~NPEs or~~ SerializationExceptions on startup. 

### What I expected to happen
The `SchemaRegistryClient` should support any `CacheManager` implementation to cache schemata locally client-side

_Edit: Struck out some things to refocus on `Redis`_

**Comment by dmarmugi** [comment]
I think I figured one part (the NPE) out, which makes the `caffeine` cache seem to work, at least: the caches need to be declared, they're not created-if-missing: 
in `application.yml`: 
```yaml
    cache-names: demo,org.springframework.cloud.stream.schema.reflectionCache,org.springframework.cloud.stream.schema.referenceCache
```

Those caches are defined in `org.springframework.cloud.stream.schema.avro.AvroSchemaRegistryClientMessageConverter`. IMO, this is obscure enough that the `AvroMessageConverterAutoConfiguration` should make an attempt at creating them during initialization.

**Comment by dmarmugi** [comment]
Spun off the above comment into a separate issue, and going to re-frame this one as specific to the redis cache (which may put it out of scope/won't fix?).

**Comment by olegz** [comment]
I am not sure I follow. 
I got your example running, I do see the same exception, but it doesn't appear to be in any way related to missing caches. 
First if you look at implementation of the cache manager (`RedisCacheManager` for your case), they do create caches if they are missing, so I can't reproduce NPE you're referring to.

Now, the exception simply tells me you're simply dealing with object that `RedisCacheManager` can not serialize. In fact by removing Redis, everything works with the other cache manager. So if anything it seems like the real issue is with `RedisCacheManager`.

Am I missing something?

**Comment by dmarmugi** [comment]
Hi @olegz -- nope, that's what I was trying to do by splitting the issues: this one was for what seems to me to be that Redis doesn't work as a cache manager for `SchemaRegistryClient`. 

At this point I don't know whether it belongs in this project or maybe `Spring Redis`? If the problem is that Redis as a cache provider expects the payload to `implements Serializable`, but Avro `SpecificRecord` schemas don't?

**Comment by olegz** [comment]
Yes, I would say this issue should definitely be raised with Spring Redis as it appears that there is some disconnect between Avro SpecificRecord and Redis Serializable. So feel free to close and open a new one in Spring Redis with a small example of trying to put avro object in redis cache which should fail with the same stack trace

**Comment by dmarmugi** [comment]
Thanks, I'll see what I can whip up.

**Comment by moroneyk** [comment]
Did you get this issue sorted? I am seeing the same behaviour

**Comment by olegz** [comment]
I am actually going to close this issue as "Won't fix" as there is nothing to fix on stream side. As you can see from the discussion the issue is specific to Redis cache as it has certain expectation which are not the same as other caches. As I suggested earlier, consider raising the issue wit data team that manages Redis cache configuration.
