### ISSUE TITLE
EnableBinding breaks ConfigurationProperties validation

### ISSUE THREAD

**Issue by kkrawczy** [spring-cloud/spring-cloud-stream#1573]
Once binding to the broker is enabled (@ EnableBinding) the validation of ConfigurationProperties stops working. The example project: https://github.com/kkrawczy/props-validation-demo
The versions:
spring-boot-starter-parent: 2.1.1.RELEASE
spring-cloud-dependencies: Greenwich.RC2

Explanation:
I have a configuration properties class:
```
@Component
@ConfigurationProperties("props")
@Validated
public class ValidatedProps {
    @NotBlank
    @NotNull
    @Pattern(regexp = "\\d{3}-\\d{3}-\\d{4}")
    private String ohlala;
}
````
Property `ohlala` is not present, so while starting the context I get validation errors. That is a correct behavior.
But once `@EnableBinding(Queues.class)` is added, the validation is omitted and I can start the app.

After a quick investigation, it seems that the problem is BindingHandlerAdvise that creates BindHandler without validation capabilities.

Thx for help.

**Comment by olegz** [comment]
This is related to the following commit https://github.com/spring-cloud/spring-cloud-stream/commit/10e85429e076501609e0d408468ec6a7064955cd which is was done in conjunction with the boot change (the addition of `ConfigurationPropertiesBindHandlerAdvisor`) to simplify the merge between the default and binding specific properties. 

Unfortunately we used simple [BindingHandler](https://github.com/spring-cloud/spring-cloud-stream/commit/10e85429e076501609e0d408468ec6a7064955cd#diff-e43ba23cdfa9cffee4428964168d839bR53) in its implementation.

Fortunately to address this all we need is to pass the Validator and use `BindHandler handler = new ValidationBindHandler(validator) {`

I just verified it, so will be fixed in time for 2.1.0.RELEASE.
