### ISSUE TITLE
Ensure multiple instances of IntegrationFlow bean do not create conflict

### ISSUE THREAD

**Issue by tamast** [spring-cloud/spring-cloud-stream#1581]
Hi,

I cannot start Spring Boot application using Spring Cloud Stream 2.1.0.RC4  if there is more then one IntegrationFlow beans and my application has a bean that extends org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.

The same code works with Spring Cloud Stream 2.0.0.RELEASE

for example:

```java
    @Bean
    public IntegrationFlow myIntegrationFlow1() {
        return IntegrationFlows.from(...)
				....
                                .get();
    }
	
	
    @Bean
    public IntegrationFlow myIntegrationFlow2() {
        return IntegrationFlows.from(...)
				....
                               .get();
    }
```

The application start fails with: 

`Field integrationFlow in org.springframework.cloud.stream.binder.AbstractMessageChannelBinder required a single bean, but 2 were found:...`

I replaced the IntegrationFlow with  route and subFlowMappings, but what I achived is the number of integrationFlow beans increased (because I replaced the two IntegrationFlows with one IntegrationFlow and 3 subFlowMappings) and I get the same error:

 `Field integrationFlow in org.springframework.cloud.stream.binder.AbstractMessageChannelBinder required a single bean, but 4 were found:...`

```java
    @Bean
    public IntegrationFlow myMainIntegrationFlow(X) {
        return IntegrationFlows.from(...)
            .route("...", spec -> spec
                .subFlowMapping("...", integrationFlowDefinition -> {...}))
                .subFlowMapping("...", integrationFlowDefinition-> {...}))
                .subFlowMapping("...", integrationFlowDefinition-> {...}))
				....
                .get();
    }
```

if I add `@Primary` annotation to my integrationflow the app could start and it solves the problem.

```java
    @Primary
    @Bean
    public IntegrationFlow myMainIntegrationFlow(X) {
        return IntegrationFlows.from(...)
            .route("...", spec -> spec
                .subFlowMapping("...", b -> {...}))
                .subFlowMapping("...", b -> {...}))
				....
                .get();
    }
```

This issue was probably introduced here: https://github.com/spring-cloud/spring-cloud-stream/issues/1553

Should this field be a list here?

https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L124

and here maybe just check if integrationFlow list is empty:
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L823

**Comment by olegz** [comment]
The framework wasn't really designed to be a general purpose container to host multiple IntegrationFlows, so I would be curious as to what is your use case. 
The fact that it may have worked before 1553 is a lucky coincidence. 

Anyway, could please elaborate as to what are you trying to accomplish?

**Comment by artembilan** [comment]
I think the problem here, @olegz , that you fully don't give any chances for end-users to use an `IntegrationFlow`.
In the `FunctionConfiguration` you have this bean definition:
```
@ConditionalOnMissingBean
@Bean
public IntegrationFlow integrationFlowCreator(IntegrationFlowFunctionSupport functionSupport) {
```

OK. This really can be omitted because of `@ConditionalOnMissingBean` when end-user provides his/her own `IntegrationFlow` bean(s), but at the same time in the `AbstractMessageChannelBinder` we have this:
```
@Autowired(required = false)
private IntegrationFlow integrationFlow;
```

Are you really sure that any `IntegrationFlow` can be injected here?

On the other hand this is really not good from Spring Integration perspective and you fully eliminate all its Java DSL goodies.

In fact I believe you wanted to say something like this:
```
@Autowired(required = false)
@Qualifier("integrationFlowCreator")
private IntegrationFlow integrationFlow;
```

So, the question is: what is the point don't allow end-users to configure their microservice logic via `IntegrationFlow`s? Not that flows can be nested, e.g. router.

Thanks

**Comment by olegz** [comment]
My point was not about `IntegrationFlow` or not `IntegrationFlow`. It was more about having more then one top level integration flows, which is what I believe is at the core of the issue here.

**Comment by olegz** [comment]
The `@Qualifier("integrationFlowCreator")` though is probably a valid argument since the code mentioned above is specific to Spring Cloud Function support and should probably be scoped as such.

**Comment by artembilan** [comment]
One more time: You may have a single `IntegrationFlow` top level definition, but since you may have a nested brances, like for router, you'll end up with beans for them as well. Even if ti is not so explicit from the configuration, everything must be as a bean. Otherwise we can't configure a runtime model properly.
So, you must have a `Qualifier` and also that `@ConditionalOnMissingBean` should have a `name="integrationFlowCreator"` as well. 

It doesn't look legitimate to override that bean unconditionally and also doesn't look logical to continue some post-configuration in the mentioned `AbstractMessageChannelBinder` for any `IntegrationFlow`. I mean we need to be restricted only to the `integrationFlowCreator` there as well, like we have already agreed.

**Comment by olegz** [comment]
@artembilan please re-read my last response and the changed description of the issue.

**Comment by alwyn** [comment]
I know this is closed, but here is a use-case.

I'm using cloud stream to receive messages and send responses from/to RabbitMQ.

My processing is such that my handler will do some processing and then use a messaging gateway to access a flow for sending a request over tcp/ip to another service, read the response and return some data.

This data is then further processed and finally returned back to the response queue.

I know all this can probably be wrapped in a single end-to-end integration flow, but I'm still learning Spring integration and this is the simplest for me at the moment.
