### ISSUE TITLE
Unknown property 'auto-bind-dlq' for type '*.binder.rabbit.properties.RabbitConsumerProperties'

### ISSUE THREAD

**Issue by jiangzhe2014** [spring-cloud/spring-cloud-stream#1586]
In the context of trying to configure rabbit bindings, the docs mention that 

> "**Unknown property 'auto-bind-dlq' for type 'org.springframework.cloud.stream.binder.rabbit.properties.RabbitConsumerProperties'** ":
> "**Unknown property 'maxPriority' for type 'org.springframework.cloud.stream.binder.rabbit.properties.RabbitConsumerProperties'** ":
> ...

`spring.cloud.stream.rabbit.bindings.input.consumer.auto-bind-dlq=true `
`spring.cloud.stream.rabbit.bindings.input.consumer.maxPriority=2 `
`...`
![springcloud stream](https://user-images.githubusercontent.com/10086575/51360393-66cd6000-1b06-11e9-934a-ede056a773c7.jpg)

the property is in `RabbitCommonProperties` the supper classes of `RabbitConsumerProperties` and `RabbitProducerProperties`.

**Comment by olegz** [comment]
That is unfortunately the limitation of the tooling. Since it does not properly interpret properties defined in based classes. 
While it's harmless, there is nothing we can do about it at spring-cloud-stream level so I'll close this issue. Please raise the issue at [STS](https://github.com/spring-projects/sts4) if you're  using STS or if IntelliJ then use their issue tracking facility.
