### ISSUE TITLE
needs extended support for spring cloud function in spring cloud stream

### ISSUE THREAD

**Issue by 5aab** [spring-cloud/spring-cloud-stream#1626]
[**Greenwich RELEASE**](https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/single/spring-cloud.html#_spring_cloud_function) introduced spring cloud function support in spring cloud stream which is very much desired feature. But as of now, function(s) can be bind with one destination(either source or sink. two in case of a processor). **is there any way to bind function(s) to the multiple destinations?** Currently, we have microservices which can publish the messages to multiple destinations( not the ideal design and debatable). is there any way to achieve it by leveraging spring cloud function support. or such a feature is planned for the near future? Thanks

**Comment by kschlesselmann** [comment]
We're running into the same issue here. We have a service that combines multiple input streams into one output stream (like `(A-in,B-in)->C-out`).

Since we're using the reactive stack to it'd be great to seamlessly read from multiple streams into a `Flux` combine those two and output one `Flux` using the Spring CLoud Function programming model.

I think this issue becomes even more urgent with the deprecation of Spring CLoud Stream Reactive in the next release.

**Comment by olegz** [comment]
Note to self: Consider addressing it together with #1590. Basically eliminate the need for `@EnableBinding` and make it purely driven by boot autoconfiguration and external properties ensuring that the app itself stays independent from _s-c-stream_, _s-c-function_ etc.

**Comment by olegz** [comment]
We were discussing support for multiple-in/out last week and it will be a theme for 2.3 (Horsham)

**Comment by olegz** [comment]
Closing it in favor of #1745 and #1746
