### ISSUE TITLE
Could configuration work if channelName has character ".",

### ISSUE THREAD

**Issue by 2oo10o** [spring-cloud/spring-cloud-stream#1680]
My channelname is like "biz.es-command".

So if I have this configuration:
'spring.cloud.stream.bindings.biz.es-command.group = es-command'

It can't work? And is there any way to solve this except changing channelname?

**Comment by olegz** [comment]
No, this won't work since `"."` is a delimiter.
Why do you have to call channel that way in the first place?  You can call it any other compatible name. In fact it doesn't even matter what you call it since the important part if the actual mapping of such channel to the remote destination `...<channel-name>.group = es-command`.

Now I am just curious, why can't you use the already provided `input` and `'output` via Source and Sink binding interfaces?

Also,I am closing this issue since it is rather a _question_, not an issue. For the future please use [stack-overflow](https://stackoverflow.com/tags/spring-cloud-stream) channel to ask question.
