### ISSUE TITLE
@IdempotentReceiver annotation doesn't work with @StreamListener

### ISSUE THREAD

**Issue by 5aab** [spring-cloud/spring-cloud-stream#1728]
Looks like **@StreamListener** doesn't have support for *Advice Chain* and hence **@IdempotentReceiver** annotation doesn't work with it. can we please add support for it.

For Example
This sample project uses **@StreamListner**. and @IdempotentReceiver annotation doesn't work
https://github.com/5aab/RabbitSpringCloudSream

This sample project uses **@ServiceActivator** Annotation and @IdempotentReceiver annotation works fine
https://github.com/5aab/SpringItegrationIdempotent

please let me know if more information is required. Thanks

**Comment by olegz** [comment]
@5aab We are actually considering deprecating `@StreamListener` in favor of spring-cloud-function programming model that has been available in s-c-stream since 2.0.0 and we are working on additional features and enhancements within that model. 
Also, as you yourself indirectly pointed out there is an element of redundancy between `@StreamListener` and `@ServiceActivator`, so there should be no issues or concerns for using `@ServiceActivator` or the entire SI stack of patterns if you need certain feature. that falls outside of realm of simple message handler.

So, in a way we are rejecting this request for the reasons mentioned above.
