### ISSUE TITLE
Support SpEL expression for inputchannel error

### ISSUE THREAD

**Issue by mjmunizsa** [spring-cloud/spring-cloud-stream#1731]
I have different Kineses channels for development and production. I'm using application error handling with an error channel for each binder, but I can't customize the inputchannel 
 in @ServiceActivator annotation with a property.

I'm going to simplify the use case, although the real use case is more complex.

A single channel with a different name in development and production:

- application-DEV.properties
```
spring.cloud.stream.bindings.input.destination=channel-1-dev
spring.cloud.stream.bindings.input.group=mygroup
#I want to inject into annotation but not working
channel-error=channel-1-dev.mygroup.errors
```
- application-PRO.properties
```
spring.cloud.stream.bindings.input.destination=channel-1-pro
spring.cloud.stream.bindings.input.group=mygroup
channel-error=channel-1-pro.mygroup.errors
```

- Listener channel. handleError method notWorking
```
@Slf4j
@EnableBinding(Sink.class)
public class ChannelListenerOne {

        @StreamListener(Sink.input)
	public void subscriberChannelOne(Message<?> message) {
            throw new RuntimeException("Boom");
        }

        @ServiceActivator(inputChannel ="${channel-error}")
	public void errorHandle(Message<?> message) {

		log.error("Error at consumer {}: {}",
			this.getClass()
				.getSimpleName(),
			message);
	}
}
```
I've tried concatenating the properties and it doesn't work either.
It only works if I indicate the inputChannel property with a string or a constant explicitly. But in this case I won't be able to customize the name of the channel by environment.

```
       @ServiceActivator(inputChannel ="channel-1-dev.mygroup.errors")
	public void errorHandle(Message<?> message) {

		log.error("Error at consumer {}: {}",
			this.getClass()
				.getSimpleName(),
			message);
	}
```

It is possible to use properties with the annotation @ServiceActivator?.

Thanks.

**Comment by artembilan** [comment]
No, that's not possible. The `inputChannel` is a bean reference and it never was possible to have customized bean name dependently of the environment.
This is kinda security vulnerability to be able to have a different bean name for the same object at runtime according some condition. 
Bean name in Spring are always constant. That's how they can reach each other from some business logic. And in this case we indeed need to have some particular `MessageChannel` bean to get access to it from this `@ServiceActivator`.

You need to think about some other solution where a channel name is fixed.

IO can suggest one variant which is possible with `@Profile`: https://docs.spring.io/spring/docs/5.1.8.RELEASE/spring-framework-reference/core.html#beans-definition-profiles-java

So, you declare several `@Configuration` classes with those different `@ServiceActivator` methods which are going to be activated only when this or that profile is enabled in your configuration.

There is another way via `IntegrationFlow` bean definition with its `.from(String channelName)` and `@Value` resolution for channel bean name from properties: https://docs.spring.io/spring/docs/5.1.8.RELEASE/spring-framework-reference/core.html#beans-java-combining-java-centric

I'm going to close this as *Won't Fix* because this is not what we would like to have in the Framework and there are some other ways to overcome your requirements.
