### ISSUE TITLE
spring cloud stream test binder manual acknowledge is not working

### ISSUE THREAD

**Issue by guru2228** [spring-cloud/spring-cloud-stream#1752]
Hi Team,

I am using Spring Boot 2.1.3 and Spring Cloud Greenwich.RELEASE. I am trying to do Manual Commit in Spring Cloud Stream using Kafka, it is working as expected when i run the app as Spring boot App pointing to my local Kafka, but when i run my test cases where the test binder does not send an acknowledgement in the headers. Please let me know how can i make my tests to cover the below lines of code in the method annotated with @StreamListener

if (acknowledgment != null) {
	acknowledgment.acknowledge();
}

**Comment by olegz** [comment]
The test binder would not be acking/nacking anything since it's just a mock to wire up your test.
Also, keep in mind that  `acking/nacking ` is in general specific to the capability provided by the actual broker (e.g., kafka, rabbit etc), so it should not be expected from a general purpose test binder . 

I will close this issue since there is no action to be taken. In the future please use [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-cloud-stream) channel for asking question. This issue tracker is for rasing the actual issues (bugs, feature requests etc.)
