### ISSUE TITLE
Suspending streaming listener

### ISSUE THREAD

**Issue by senthilsivanath** [spring-cloud/spring-cloud-stream#1780]
Using spring cloud stream with kotlin coroutines. 

@StreamListener annotation is not accepting suspend keyword, so in the listener method unable to call any await method of coroutines. 

Tried using spring cloud reactive which expects Flux<?> as output but unable to pass coroutine output to spring cloud output. Any pointer could be helpful.

**Comment by senthilsivanath** [comment]
Got it working. Log printed no elements when i did collect for debugging, realised fluxproducer.send should be used while converting from coroutine scope and reactive. 

```kotlin
@StreamListener
    @Output(Processor.OUTPUT)
    fun receive(@Input(Processor.INPUT) inputData: Flux<String>): Flux<String> {
        return inputData.log().flatMap {
            CoroutineScope(GlobalScope.coroutineContext).flux<String> {
                val output = getResponse() // suspendable function
                this.send(output)
            }.log()
        }
    }
```

**Comment by olegz** [comment]
I'll close it since it appears there is no issue. Keep in mind though that reactive module you are using is deprecated and will not be part of 3.0.0 release. The same goes for `StreamListener`, although we will support it for a bit longer.

The reactive code above is supported natively via spring-cloud-function (which is a dependency of spring-cloud-stream), so all you need is rewrite your code as such:
```
@Bean
public Function<Flux<String>, Flux<String>> receive() {
. . .
}
```

. . . and `supply spring.cloud function.definition=receive` property.

See more [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.0.M3/reference/html/spring-cloud-stream.html#spring_cloud_function)
