### ISSUE TITLE
Cannot find a @StreamListener matching for message with id

### ISSUE THREAD

**Issue by sabareeshkkanan** [spring-cloud/spring-cloud-stream#1849]
Greenwich.SR3
We are using conditional parameter to route request to different microservices. So based on some header condition a message might go to Service A or Service B, but not both. So we are getting this warning on the service which it doesnt have a handler that matches this condition. Is it safe to ignore this warning ? if so can we disable this warning with some property ?.

May not be related but we are getting hit with memory issue after this implementation 
````{"message":"Error while stopping the container: ","exception":{"exception_class":"java.lang.OutOfMemoryError","exception_message":"Java heap space","stacktrace":"java.lang.OutOfMemoryError: Java heap space\n"},"@version":1,"source_host":"11969b115b00","thread_name":"Thread-15","@timestamp":"2019-11-20T16:57:12.297+00:00","level":"ERROR","logger_name":"org.springframework.kafka.listener.KafkaMessageListenerContainer","env":" uat"}````

**Comment by olegz** [comment]
With regard to OOM it's impossible for us to answer since we know nothing about your application. 
With regard to routing and conditions consider reading these two blogs where we're explaining why we're moving away from the annotation-based programming model:

- https://spring.io/blog/2019/10/14/spring-cloud-stream-demystified-and-simplified
- https://spring.io/blog/2019/10/31/spring-cloud-stream-event-routing

Also, next time when asking question please use appropriate [Stack Overflow channel](https://stackoverflow.com/tags/spring-cloud-stream) as this issue tracker is not monitored for questions by our user community.
