### ISSUE TITLE
Unable to use payload for partitioning under new functional API

### ISSUE THREAD

**Issue by mkheck** [spring-cloud/spring-cloud-stream#1893]
Attempting to use payload per docs in order to filter/route to partitions no longer works when using the functional API (vs. previous annotation-driven approach with input/output channels, etc).

**Comment by olegz** [comment]
Just to add a little context, supposed you have the following configuration:
```
--spring.cloud.stream.bindings.func-out-0.producer.partitionKeyExpression=payload.id"
--spring.cloud.stream.bindings.func-out-0.producer.partitionCount=5"
```
. . . you will end up with 
```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'id' cannot be found on object of type 'byte[]' - maybe not public or not valid?
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:217)
	at or. . . 
```

That is understandable, especially in function model where the type conversion from/to wire format happens right before and after the function invocation. This means that the payload seen by SpEL evaluation is always `byte[]` (regardless of what was produced by the function).

On one hand this is consistent to an already established and documented ([see the end of the section](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.1.RELEASE/reference/html/spring-cloud-stream.html#_using_streamlistener_for_content_based_routing)) rule for input where we recommend to apply SpEL on headers. We probably need to make it a bit more clear in the docs and make it specific to the function (not just legacy annotation-driven approach).

That said, I am (at least at the moment of this writing) reluctant to introduce any exception to this rule for outputs.

The core argument is that `payload` is considered to be _privileged information_, similar to the letter inside he envelope, the contents of which shared only between he sender and the receiver. The post people make their decision strictly based on meta-information provided on the envelope (equivalent to message headers). 

So with that said, I believe this is really a documentation issue which probably would need it's own section rather than a note or callout that is easy to miss, but i'll sleep on it.

**Comment by olegz** [comment]
Duplicate to https://github.com/spring-cloud/spring-cloud-stream/issues/1877

**Comment by mkheck** [comment]
Hmm...the fix doesn't work for Supplier. :/
