### ISSUE TITLE
In document `spring.cloud.stream.bindings.input.group=hello` will not work

### ISSUE THREAD

**Issue by ozooxo** [spring-cloud/spring-cloud-stream#1914]
In document it is talking about reset the queue name

> Go to the RabbitMQ management console or any other RabbitMQ client and send a message to input.anonymous.CbMIwdkJSBO1ZoPDOtHtCg. The anonymous.CbMIwdkJSBO1ZoPDOtHtCg part represents the group name and is generated, so it is bound to be different in your environment. For something more predictable, you can use an explicit group name by setting spring.cloud.stream.bindings.input.group=hello (or whatever name you like).

(https://github.com/spring-cloud/spring-cloud-stream/blame/528eaf041a7fb86c6c778c33ddc09c3881641009/docs/src/main/asciidoc/preface.adoc#L141)

It will not work. In case you have a method name `log`

```
public Consumer<Person> log() {
```

it will work when you

```
spring.cloud.stream.bindings.log-in-0.group=hello
```

Or if you define

```
spring.cloud.stream.function.bindings.log-in-0=input
```

and then

```
spring.cloud.stream.bindings.input.group=hello
```

Should probably update the document, and link to the [section about "function binding names"](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.2.RELEASE/reference/html/spring-cloud-stream.html#_functional_binding_names).

**Comment by olegz** [comment]
That is correct, with functional programming model the binding names derive from function names, so in your case `log-in-0` is the binding name that should be referenced in properties `spring.cloud.stream.bindings.log-in-0.group=hello`. 
However if you don't like the derived name you can remap it to something more meaningful to you - `spring.cloud.stream.function.bindings.log-in-0=input` and from that point on you should use that binding name instead of derived binding name = `spring.cloud.stream.bindings.input.group=hello`.

So I don't see any issue here, but please feel free to re-open it if you believe there is something more to discuss.
