### ISSUE TITLE
Improve Ability to Publish to Multiplex/Dynamic Destinations

### ISSUE THREAD

**Issue by Mrc0113** [spring-cloud/spring-cloud-stream#1950]
**Describe the issue**
Currently when publishing to dynamic destinations each one seems to create a new Spring Integration Channel that is never cleaned up. For a use case where your application will be publishing to thousands or potentially millions of topics of time this causes performance + memory issues within the Spring Boot microservice. 

An example use case is publishing flight events with a rich topic hierarchy defined something like this: `faa/tfms/<Departure Airport Code>/<Arrival Airport Code>/<Airline>/<Flight Number>`  to allow for consumers to filter on exactly which events they want to consume. Only for a certain airline, arrival airport, etc.  

**To Reproduce**
This repo holds an example app that reproduces the memory/performance issue. Note that it does not show a business use case but just publishes to dynamic topics in a loop.

**Version of the framework**
Latest

**Expected behavior**
Application performance + memory should remain steady over time when publishing to dynamic/multiplex destinations just like an application using Spring Integration + a jms template does in a similar situation. Also, ideally the developer should not have to "learn messaging apis" to take advantage of this. 

**Screenshots**
This image shows metrics found running the sample app above. 
![image](https://user-images.githubusercontent.com/1815312/80758319-7b6b1700-8b03-11ea-8a94-f49314d99ae7.png)

**Additional context**
@garyrussell @olegz this is the issue we discussed on our call. With your knowledge of the internals of how SCSt + SCF + Spring Integration are built it sounds like you already had a fix in mind. Appreciate your help!

**Comment by garyrussell** [comment]
One more thing, which I don't think came up on the call (and a reason to keep the existing functionality @olegz ) is the provisioning aspect.

Currently, when a new destination binding is created on the fly, the whole provisioning process takes place (e.g. for rabbit, the exchange is declared and, optionally, queues bound to the exchange).

With the new "lightweight" dynamic routing proposed on the call (and already supported by the RabbitMQ binder - via `routingKeyExpression`), there will be no provisioning support and either the destinations need to be pre-provisioned or the middleware will need to support auto-provisioning of the destination.

(Or a new provisioning model will be needed).

**Comment by Mrc0113** [comment]
Hi @garyrussell. Maybe I'm missing something here but I don't see an issue with that. The framework would still be leveraging the binder to publish messages to the broker itself so if something special had to be done to support this for specific middleware it could be added in the binder abstraction. 

In the case of Solace, like Rabbit, there shouldn't be any extra work here. In Solace when publishing to a topic it's just a header on a message used for routing so no provisioning is necessary.

**Comment by olegz** [comment]
@Mrc0113 what Gary is saying is that we need not assume some magic with regard to provisioning. In other words we should still rely on the provisioning part of the framework when introducing the lighter approach.

**Comment by Mrc0113** [comment]
@olegz, thanks for the clarification. That makes sense to me.

**Comment by olegz** [comment]
I'll work on this tomorrow so should be available in the snapshots for you some time this week

**Comment by garyrussell** [comment]
>what Gary is saying is that we need not assume some magic with regard to provisioning. In other words we should still rely on the provisioning part of the framework when introducing the lighter approach.

@olegz @Mrc0113 I am actually saying the opposite of that.

If you use the new "lightweight" approach we **don't want to provision for each dynamic destination** (because we'll still get an exchange per destination with RabbitMQ, which is not what we want). The RabbitMQ binder already supports the lightweight approach via its `routingKeyExpression` producer property. But when that mechanism is used, only one physical binding (to an exchange) is provided and we can optionally bind queues to that (via the `requiredGroups` property.

The Solace binder could support the same approach today without any changes to the core framework. Simply use a custom header on outbound messages and use that header in the single output binding to route to the desired queue/topic.

All I was trying to say is that for some use cases, the "heavyweight" approach is still required, where the user expects the provisioning to occur.

**Comment by olegz** [comment]
For Rabbit due to it's internal routing mechanism (exchange -> queue) you are correct, unless we follow some convention and pre-create some router exchange once and then use `routingKey`.

The way I understood this is that provisioning and the memory leak associated with channels and other binding/integration objects created as a result of provisioning are two different concerns. In other words look at them separately where I can/should still use provisioning for dynamic destinations, but skip the rest.

**Comment by garyrussell** [comment]
JmsTemplate has send methods that take the destination alongside the data.

The Spring Integration `JmsSendingMessageHandler` (which I assume is used by the Solace binder) has `setDestinationExpression` - it would work just like the RabbitMQ binder's `routingKeyExpression`.

I think the only thing the core framework needs to do is define a standard header that can be used by any binder (if it supports this style of dynamic routing) so that the application is able to switch binders without code changes.

**Comment by garyrussell** [comment]
>I think the only thing ...

And maybe a new producer property `enableDynamicDestinations` which is used by binders to set up default routings, e.g. the RabbitMQ binder can set the `routingKeyExpression` to use that header as a routing key, if not explicitly set by the user.

**Comment by Mrc0113** [comment]
Hi @garyrussell, just as a FYI - the Solace binder actually uses JCSMP (the Solace Java Library), not JMS. However, just like JMS, JCSMP also has a send method that takes the message alongside the destination so I believe your suggestion would work just fine. 

Without knowing the internals of the SCSt. framework code very well your proposal makes sense to me. If I read it correctly a default destination for a given binding would be defined (I would assume the same as now) and then if a binder wants to support this feature it would be responsible to check if the `enableDynamicDestinations` producer property is set to `true` and if so the binder would check for existence of a message header that defines the dynamic destination and handle the publishing to that destination on a message per message basis.

**Comment by olegz** [comment]
I am actually spiking out slightly different and binder-independent solution.
Basically provisioning aspect is handled by the binder in a manner _"if exist use it if not create and use it"_ and that is actually not the issue you are having.
The fact that we create a `MessageChannel`, `MessageHandlers` etc for each new destination is also not your issue although things could probably be simplified there as well.

However, the fact that we are registering those channels in the `BeanFactory` is the actual issue.

**Comment by Mrc0113** [comment]
Sounds good @olegz. I'll follow along silently and let you and @garyrussell as the masterminds figure out the path forward. Feel free to tag me if you want my input.

**Comment by garyrussell** [comment]
@Mrc0113 FYI; you can do this today with a custom (solace-specific) header.

If the header is present in the message, use it to determine the destination; if it's not there fall back to the default destination.
