### ISSUE TITLE
StreamBridge should skip conversion if native encoding is enabled. 

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#1998]
When native encoding is enabled, the `StreamBridge` API still tries to convert using the default converter causing runtime exceptions.

**Comment by D3jank** [comment]
Can we expand on this? Since your conversion code executes `MessageBuilder`, we are unable to pass our own Message<?> object and thus cannot send custom headers nor a key to our kafka topics using stream bridge. As I mention here in the comments following your response: https://stackoverflow.com/questions/62641008/how-to-configure-spring-cloud-streambridge-to-produce-avro
