### ISSUE TITLE
Why does a consumer have to specify a group name in order to get pub-sub?

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#211]
I would have thought it would be the default if the destination is a "topic" (I think it used to be). Can anyone explain why this extra step is necessary?

**Comment by garyrussell** [comment]
The bug was it could never be a topic in s-c-s (after the port from XD), but we __do__ need to support competing consumers on a topic (so we can have multiple instances of a stream module consuming from a tap, for example). So we introduced the concept of a consumer group.

I agree though, that the default (no group) should mean a topic is a topic. We should change the default to use a UUID if there's no group supplied.

**Comment by garyrussell** [comment]
OTOH, if the subscription is durable, a UUID would not work - a durable subscription would __have__ to provide a group.

**Comment by garyrussell** [comment]
@sabbyanandan this should be added to the next sprint.

**Comment by garyrussell** [comment]
@dsyer @markfisher There is a problem with the bus assigning a unique random group when none is provided - we can't know which consumer to stop/remove when unbinding.

That is ok if the consumer simply stops (e.g. JVM exit), since the queue is auto-delete, but it won't work if the app wishes to programmatically unsubscribe.

This is not a problem for s-c-df because it will always provide the group, but I don't think it's tenable for the general case.

I see a couple of options:

1. Status quo - caller has to provide the group
2. Change the API to return the group when binding so it can be used to unsubscribe - caller is responsible to pass it back in

Thoughts?

**Comment by mbogoevici** [comment]
@garyrussell Would retaining the group as part of the `Binding` help in any way ?

**Comment by markfisher** [comment]
This probably does not answer the question, but we should think ahead to the point where we remove the topic/queue distinction (and the prefix). Will that impact the decision we make? Specifically would that make it so that assigning a random UUID is not really the appropriate behavior?

**Comment by garyrussell** [comment]
@mbogoevici unfortunately, no; let's say two consumers bind to the pubsub - they want true pubsub and provide no group; when one of them unbinds, we don't know which binding to remove.

It's ok in the normal case with one binding per JVM, but there's no such restriction imposed by the binder itself (currently).

I suppose that's another possibility - only allow one "anonymous" pubsub binding per `Binder` instance; in that case the unbind won't have to know the group to unbind.

@markfisher I don't think that's a problem - everything will be a pubsub - grouped means competing consumers on that binding, ungrouped means true topic behavior.

**Comment by mbogoevici** [comment]
@garyrussell Gak. One other option would be to maintain the current restriction at the `Binder` level and retain the used group IDs per binding as part of the `ChannelBindingService` (where each binding is guaranteed to be unique) - it is a bit of a hack, but that would provide an intermediate solution while we refactor that layer - eventually there should be more consolidation happening after #213 .

**Comment by markfisher** [comment]
Could we have the random UUID generated for the `BindingProperties` `group` property value if nothing explicit has been provided?

**Comment by garyrussell** [comment]
Actually - I see things are a bit broken now - the CBS uses the general `unbindConsumers()` which won't unbind a grouped pubSub.

As long as we can be sure that all binding is done via the CBS, I think we can manage it will a default random UUID group in the binding properties.

Code interacting with the `Binder` directly will be on its own.

**Comment by mbogoevici** [comment]
We can safely assume that all binding is done under the control of the current CBS (which we will want to clean up once the SPI code is moved over).

**Comment by garyrussell** [comment]
OK; I'll spin up a PR and you can take a look.

**Comment by mbogoevici** [comment]
@garyrussell ok cool - looking forward to it - for reference, another assumption would be that each binding will be bound only once - so we could use the binding name as a unique identifier. The reason why I would have preferred to retain the binding state (in the current case, group) rather than hack the `BindingProperties` as part of the channel binding service is that we could expose the state later through the management endpoints. We can do that as part of a larger consolidation process though.

**Comment by garyrussell** [comment]
@mbogoevici We can't use the binding name to disambiguate - 2 different apps might want to bind to the pubsub (different binder instances). From a rabbit perspective, this must map to 2 different queues.

**Comment by mbogoevici** [comment]
@garyrussell I meant within the same application, where there can only be one and only one instance of a binding with a specific name.
