### ISSUE TITLE
KafkaMessageChannelBinder escapeTopicName and underscores

### ISSUE THREAD

**Issue by Blackbaud-KevinHutson** [spring-cloud/spring-cloud-stream#217]
We have a set of Kafka topics that reflect table names from an Oracle database. These get auto-generated and we'd prefer not to change it on the Oracle producer side.

When we try something like this:
spring.cloud.stream.bindings.kafkaInputChannel=FOO_BAR

Spring is escaping this name so that you see FOO5FBAR or FOO_5FBAR, because it contains an underscore. See KafkaMessageChannelBinder#escapeTopicName.

Is there a way to disable this encoding, or express the topic name so that we can keep the underscore?

**Comment by mbogoevici** [comment]
Hi Kevin,

Thanks for the feedback.

It is not possible to disable it right now, but since the underscore is a legal character, it makes sense to be able to preserve it. We'll provide a fix to this. 

Cheers,
Marius

**Comment by Blackbaud-KevinHutson** [comment]
Thank you! Much appreciated!

**Comment by ericbottard** [comment]
While underscore is a legal character, it is used as the escape marker. You won't be able to retain your exact original name **and** be able to represent *any* name (one needs a way to know when characters have been escaped)

**Comment by mbogoevici** [comment]
The only reason why Spring XD required escaping was because of the use of the colon in `tap:`, `topic:` and `queue:`, and potentially because a stream name and its generated queues could have included non-compatible characters. We can restrict the latter, as for the former - we are removing tap topics and will be listening on the main topic for one thing, and the distinction between 'queues' and 'topics' is also slated for removal. So in the end we can do away with escaping on the long run and just rely on validation for non-desirable characters.
