### ISSUE TITLE
Default properties not working when extended consumer/producer properties exist.

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#2201]
This works:
```
spring.cloud.stream.kafka.streams.default.consumer.application-id=testKstreamWordCountFunction"
```
but when the following properties are present (either of them), the above default property does not bind. 
```
spring.cloud.stream.kafka.streams.bindings.process-in-0.consumer.consumedAs=custom-consumer",
spring.cloud.stream.kafka.streams.bindings.process-out-0.producer.producedAs=custom-producer"
```
It seems like if we provide specific extended consumer/producer properties,  the default consumer/producer properties don't have any effect. Investigate whether this is a Kafka Streams binder issue or something more fundamental at the core Spring Cloud Stream level.

**Comment by bono007** [comment]
### Summary 
This is NOT a Kafka/Streams/Rabbit binder specific issue - they all behave this way. If there is any `spring.cloud.stream.<binder-tech>.bindings.<binding-name>"` property specified, then the defaults do not get applied for `<binding-name>`. It is an all or nothing proposition.

### Details 
When **any** properties are available under `spring.cloud.stream.<binder-tech>.bindings` the SpringBoot config props MapBinder will use JavaBeans and ultimately call [setBindings](https://github.com/spring-cloud/spring-cloud-stream/blob/5171bbe0ac8ddedb8adcb46219d3e355c4673869/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractExtendedBindingProperties.java#L51) with the available properties. 

From our example, lets look at 
```yaml
spring.cloud.stream.kafka.streams.bindings.process-in-0.consumer.consumedAs: custom-consumer. 
```
This results in `AbstractExtendedBindingProperties.bindings` to be populated w/  
```java
"process-in-0" -> KafkaStreamsBindingProperties(with `consumer.consumedAs=custom-consumer`)
```
Then when [getExtendedConsumerProperties](https://github.com/spring-cloud/spring-cloud-stream/blob/5171bbe0ac8ddedb8adcb46219d3e355c4673869/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractExtendedBindingProperties.java#L58) is called, the `bindIfNecessary` does not call `bindToDefault` since it has the key in the bindings map already.  Again, this is not specific to the `<binder-tech>` extended props - they all do this.

The comment on `AbstractExtendedBindingProperties.bindIfNecessary` also reflects this behavior:
```java
/*
 * The "necessary" implies the scenario where only defaults are defined.
 */
private void bindIfNecessary(String bindingName) {
  if (!this.bindings.containsKey(bindingName)) {
    this.bindToDefault(bindingName);
  }
}
```
However, this impl seems to generally contradict the sentiment in [ExtendedBindingProperties](https://github.com/spring-cloud/spring-cloud-stream/blob/5171bbe0ac8ddedb8adcb46219d3e355c4673869/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/ExtendedBindingProperties.java#L44) which leads me to believe the defaults are additive rather than replacement. 

### Next Steps

It seems it would be nice to respect the defaults for each `<binding-name>` and allow the specific properties to of course override the default. 

This would look like the following for our example above:
```yaml
spring.cloud.stream.kafka.streams.default.consumer.application-id: testKstreamWordCountFunction

spring.cloud.stream.kafka.streams.bindings.process-in-0.consumer.consumedAs: custom-consumer. 
```
Results in `AbstractExtendedBindingProperties.bindings` to be populated w/  
```java
"process-in-0" -> KafkaStreamsBindingProperties(with
       consumer.application-id: testKstreamWordCountFunction
       consumer.consumedAs: custom-consumer)
```

This could however, be an unexpected change for existing apps using both default and binding properties. 

@sobychacko wdyt?

**Comment by bono007** [comment]
Ok I dug a bit more and I believe the Rabbit and Kafka binders seem to have this case accounted for w/ their extended default mappings of 

https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/main/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/config/ExtendedBindingHandlerMappingsProviderConfiguration.java#L41

and 

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/a8c948a6b25699abfdededc42cf371970bdf04e4/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/ExtendedBindingHandlerMappingsProviderConfiguration.java#L41.

I believe that adding an additional default mapping entry to [ExtendedBindingHandlerMappingsProviderConfiguration](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/a8c948a6b25699abfdededc42cf371970bdf04e4/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/ExtendedBindingHandlerMappingsProviderConfiguration.java#L43) will fix this. It already has mappings for:
```
spring.cloud.stream.kafka.bindings
spring.cloud.stream.kafka.streams
```
but no mapping for `spring.cloud.stream.kafka.streams.bindings`.

I will try that out tomorrow.

**Comment by bono007** [comment]
@sobychacko we should transfer this issue back to SCSBK. My commit message references gh-2201 (which does not exist in the SCSBK - I forget the issue was in SCS before I commit etc..)

**Comment by sobychacko** [comment]
@bono007 I will move this to Kafka binder.

**Comment by sobychacko** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-binder-kafka #1152](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1152) via [**ZenHub**](https://www.zenhub.com/)
