### ISSUE TITLE
Support for Kafka 3.0.0

### ISSUE THREAD

**Issue by jomach** [spring-cloud/spring-cloud-stream#2310]
Currently if we take the dependency org.springframework.cloud:spring-cloud-stream-binder-kafka-streams:3.2.2 we get kafka-streams 2.8.1. 

Is this a bug ? If not When is 3.1.0 being supported bei spring ?

**Comment by garyrussell** [comment]
?

I just created a new project (using start.spring.io) and it pulled in spring-boot 2.6.4, spring-cloud-stream 3.2.2, spring-kafka 2.8.3, and kafka-clients, kafka-streams 3.0.0.

spring-kafka 2.8.x has always used, and will continue to use 3.0.x (2.8.4 uses the 3.0.1 kafka jars), but is compatible with 3.1.0 since 2.8.3 so you can override the version if you need to.

**Comment by jomach** [comment]
Ok, thx. My issue was using the wrong version of confluent with spring.
