### ISSUE TITLE
Remove hard dependency on KafkaAutoConfiguration

### ISSUE THREAD

**Issue by chringwer** [spring-cloud/spring-cloud-stream#2349]
There are situations where we need to stick to a certain version of the Kafka client library. With spring-boot we can opt-out of it applying its `KafkaAutoConfiguration` and set `${kafka.version}` and `${spring-kafka.version}` as needed while still benefitting from other spring-boot features in the rest of the application.

However, in `KafkaBinderConfiguration` (and also the streams binder variants) there is a hard `@Import` for `KafkaAutoConfiguration` which by-passes the support for exclusion and ordering of AutoConfigurations. Would it be possible to use `@AutoConfigureAfter` or, preferably, create a dedicated `KafkaConfiguration` class in `spring-cloud-stream-binder-kafka-core` which would bail out if the required beans are already provided by AutoConfiguration? That way the dependency on spring-boot becomes optional.

https://github.com/spring-cloud/spring-cloud-stream/blob/6c8423365adebac2bdee4c3ccb0ca5c01a8d00e9/binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfiguration.java#L84

**Comment by sobychacko** [comment]
@chringwer Sounds like something we can do. Feel free to issue a PR, or we can get to it at some point during the 4.0.x timeline.

**Comment by onobc** [comment]
This is similar to what was done in the [RabbitBinder and RabbitAutoConfiguration](https://github.com/spring-cloud/stream-applications/pull/217).

**Comment by onobc** [comment]
```
Legend
---------------------------------
SB = SpringBoot
KAC = KafkaAutoConfiguration
ACA = AutoConfigureAfter
```

### Current use of KAC
SB KAC is used in the following ways by the binder:

#### Standard config
When the app uses standard binder config then the app context is shared w/ the binder so the SB KAC is used. However, if SB KAC is excluded then the directly imported KAC is used.

#### Custom config
When the app uses custom binder config then the app context is not shared w/ the binder so the directly imported KAC is used.


### Possible solutions

#### AutoConfigureAfter
Because KAC is not recognized as typical SB auto-config, ACA does not apply in this case. If you add it to the binder configs it has no effect.

#### KAC removal
The only KAC configured bean needed by the binder is _KafkaProperties_. The binder constructs its own admin client, producer, consumer, etc.. This is a good thing. As such, simply replacing the direct `@Import` of KAC w/ `@EnabledConfigurationProperties(KafkaProperties.class)` works well.

With this approach, the required _KafkaProperties_ is available in all cases (standard/custom config w/ or w/o KAC excluded).

I submitted a code proposal w/ the "KAC removal" approach. I have added a test in each binder integration test suite to verify the case w/ and w/o KAC excluded.

**Comment by chringwer** [comment]
Thanks! That would certainly be an improvement. However, it will still leave the spring-boot dependency in place. If in a future spring-boot version `KafkaProperties` are renamed or otherwise modified in a backwards incompatible way, we would still have no option to pin the kafka dependencies to a particular version while staying up-to-date with the rest of the stack. I think, ideally there should be no hard compile time dependency to any of the autoconfiguration modules.

**Comment by onobc** [comment]
@chringwer 

I understood the original ask as the ability to use another version of `kafka-clients` / `spring-kafka` via adjusting version numbers properties and excluding KAC. I believe the above approach does allow this as KP only reliance on `kafka-clients` / `spring-kafka` is for constants (see below) which are rather stable.

```java
import org.apache.kafka.clients.CommonClientConfigs;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.config.SslConfigs;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.kafka.common.serialization.StringSerializer;

import org.springframework.kafka.listener.ContainerProperties.AckMode;
import org.springframework.kafka.security.jaas.KafkaJaasLoginModuleInitializer;
```

Another benefit of this approach is a much smaller blast radius as SCSK apps that are currently configured using `spring.kafka.*` need no further modifications. If we were to distill the required properties into a SCS config props abstraction then those apps would have to update their `spring.kafka.*` properties to a new SCS property prefix.  

While not perfect, I think it is a good compromise that allows another version of `kafka-clients` / `spring-kafka` to be used and also respecting the exclusions of KAC. 

Wdyt?

**Comment by chringwer** [comment]
Thanks, @onobc. I agree with your assessment and think this is probably good enough and our best option. Just wanted to make sure we are on the same page about the limitations of this solution. As you pointed out there are dependencies in `KafkaProperties` on `kafka-clients`/`spring-kafka` which could potentially cause issues in the future but given the nature of this class and its dependencies that is rather unlikely as of now.
