### ISSUE TITLE
Cannot use custom annotations on the consumer side

### ISSUE THREAD

**Issue by cyuegit** [spring-cloud/spring-cloud-stream#2397]
```
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
public @interface CustomMqMonitor {
    String topic() default "";
    String type() default "";
}
```

```
@Slf4j
@Component
@Aspect
public class MetricsAspect {

    private CustomMqMetric customMqMetric;

    @Autowired
    public MetricsAspect(CustomMqMetric customMqMetric) {
        this.customMqMetric = customMqMetric;
    }

    @Pointcut("@annotation(com.been.cloud.stream.config.CustomMqMonitor)")
    public void pointcut() {}

    @Around("pointcut() && @annotation(monitor)")
    public Object around(ProceedingJoinPoint joinPoint, CustomMqMonitor monitor) throws Throwable{
        long beginTime = System.currentTimeMillis();
        MethodSignature methodSignature = (MethodSignature) joinPoint.getSignature();
        Method method = methodSignature.getMethod();
        Object[] requestParams = joinPoint.getArgs();
        Object result;

        log.info("start execute:{}", method);
        try {
            result = joinPoint.proceed();
        } catch (Exception e) {
            log.error("MetricsAspect around exception", e);
            customMqMetric.metricError(monitor, "123");
            throw e;
        }
        if(!ObjectUtils.isEmpty(result)){
            customMqMetric.metricSuccess(monitor, "123");
        }
        long cost = System.currentTimeMillis() - beginTime;
        log.info("MetricsAspect cost:{} millis,end execute:{}", cost, method);
        return result;
    }

}
```

```
 @Bean
    @CustomMqMonitor(topic = "member.member_slice", type = TYPE)
    public Consumer<School> memberMemberSlice() {
        return obj -> {
            log.info("kafkaMemberReceiver input message: {}", JSONUtil.toJsonStr(obj));
            if (RandomUtil.randomInt(1, 10) > 5) {
                int i = 9 / 0;
            }
        };
    }
```

When the program starts, it will be intercepted by AOP. But when receiving a message, it cannot be intercepted
@onobc 
I want to write custom metrics based on Prometheus。but custom annotation does not take effect

**Comment by cyuegit** [comment]
@CustomMqMonitor(topic = "member.member_slice", type = TYPE)
The consumer has used a custom annotation。
Program custom aop is no problem，i have tested

**Comment by onobc** [comment]
Hi @cyuegit ,

I was pointing this out: 

> Note that the function lambda that gets returned from the memberMemberSlice bean method is not annotated w/ the custom annotation but rather the bean method is.

but I will explain w/ a code sample. 


Let's consider a simple bean rather than a SCS consumer function.
```java
@Bean
@CustomMqMonitor(topic = "foo.topic")
public Foo fooBean() {
  return new Foo();
}

static public class Foo {
  public void doThing() {
    System.out.println("++++++ foo.doThing()");
  }
}
```

Let's also assume we have some method to invoke the foo bean (maybe MVC controller):

```java
@Autowired
private Foo fooBean;

public void doSomethingWithFoo() {
  fooBean.doThing();
}
```

When `doSomethingWithFoo` is invoked, it does not get intercepted. This is similar to how the consumer invocation does not get intercepted. It is only intercepted on bean creation because that is when the method annotated w/ `@CustomMqMonitor` is invoked. 


Now, if you adjust the example above slightly as follows, the invocation **will** be intercepted. 

```java
@Bean
public Foo fooBean() {
  return new Foo();
}

static public class Foo {

  @CustomMqMonitor(topic = "foo.topic")
  public void doThing() {
    System.out.println("++++++ foo.doThing()");
  }
}
```


Likewise, if you instead create a consumer class and mark the accept method w/ the annotation then it will also be intercepted.

```java
@Bean
public Consumer<String> memberMemberSlice() {
  return new MyConsumer();
}

static class MyConsumer implements Consumer<String> {

  @Override
  @CustomMqMonitor(topic = "some.topic")
  public void accept(String s) {
    System.out.println("********* received " + s);
  }
}
```

Of course, the goal is to not get rid of the beauty of the lambda consumer and start writing consumer impls everywhere. However, I wonder if there is something you can tweak on your aspect impl to target the "accept" method of the consumer?

**Comment by cyuegit** [comment]
My current solution is similar to yours. But it doesn't feel too elegant

**Comment by onobc** [comment]
> My current solution is similar to yours. But it doesn't feel too elegant

@cyuegit I was not suggesting my comments as a workaround but more continuing the discussion to see if we can get to an acceptable solution. If you are satisfied where you ended up that is fine too.
