### ISSUE TITLE
Cached bindings are not cleaned up in StreamBridge after the corresponding message channels are removed

### ISSUE THREAD

**Issue by JadSCode** [spring-cloud/spring-cloud-stream#2452]
Hi, 

**Version information:**
Spring Boot: 2.6.2
Spring Cloud: 2021.0.3
Spring Cloud Stream: 3.2.4

When `spring.cloud.stream.dynamic-destination-cache-size` (which by default is 10) is exceeded, the number of producer threads keeps increasing. 

To reproduce this, force the cache size to a value less than the number of your output bindings and monitor the number of producer threads being created .

Or clone this repo : https://github.com/JadSCode/spring-cloud-stream-threads-producer-issue/tree/main/multi-functions-samples/multi-functions-kafka

**Comment by sobychacko** [comment]
@JadSCode If you set the `dynamic-destination-cache-size` to a lower value, then the oldest entry will be evicted each time you reach the upper threshold on the cache. In that case, I can see that the same producer binding that just got evicted may be created again. I think the problem is that when the entry is evicted from the cache, the associated producer binding is not stopped and cleaned up. Can you confirm this is the behavior that you are seeing? In that case, we will fix this.

**Comment by JadSCode** [comment]
@sobychacko That is exactly what happening.
