### ISSUE TITLE
Update documentation to explain why framework-based error handling is not supported in reactive functions

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#2482]

**Comment by migroskub** [comment]
@olegz Please add samples and documentation for the alternative error handling approach that is officially recommended by the framework. If there is some kind of a hack that can be done to achieve a DLQ behavior this will be also worth mentioning.

Anyway, please note that for some users, this will be the most important piece of documentation on this framework, since this will guide us for the approach that we will take on all of our data pipelines.

**Comment by olegz** [comment]
@migroskub  Keep in mind that current reactive support is really just to support reactive API only. We do not support the "real reasons" why someone would want to use reactive api such as backpressure etc since the underlying binders are not reactive, so it's really just an adaptation of synchronous message handler call to reactive API. So in a way I would not recommend using reactive functions in the first place. 
We are coming out with reactive Kafka binder for the upcoming release of 4.0.0, that is where support for those things including proper error handling will exist.

**Comment by migroskub** [comment]
@olegz nobody should use this framework with the Reactive API if that’s not a usage of the Reactor Kafka binder. To me this framework is worthless without the Reactor Kafka binder since I’m using the Reactor API. What I’d expect from this issue to resolve, is the explanation for how the error handling works in spring cloud stream with the Reactive binders. I think this is pretty much a waste of time to explain how error handling works when a user uses the Reactive API + a non reactive binder, since this should not ever happen (there no real reason to do so).

If you’d still like to support this weird use case so yes, an explanation of this would be helpful. But a deep explanation for how error handling works with the Reactive binders, is much, much more important. Since this is an ideal, and real use case.

**Comment by migroskub** [comment]
What I’m looking forward here is to see explanations and examples for error handling with the Reactive binders.

**Comment by olegz** [comment]
@migroskub  The framework is used by tens of thousands of  users for many years in production so calling it worthless is a bit insulting, so keep such opinions to yourself. 
As for the reactive Kafka binder, it hasn't even been released. It is work in progress so all the docs, bells and whistles  will come in due time.

**Comment by migroskub** [comment]
@olegz sorry, that’s not what I’ve meant. I just wanted to emphasize that since this issue is targeted to 4.X release, which is from my understanding the release where the Reactor Kafka binder is at, it will make more sense that users will get encouraged for using the Reactor API with this binder, and not with the regular (even they’re well established) binders. I didn’t mean to insult, I just wanted to emphasize that after 4.X it will make sense that there will maybe be a bit of less of support for the combination of synchronous binders + Reactor API. Again, sorry if I sounded harsh.
