### ISSUE TITLE
Consider Detecting Incorrectly Using StreamBridge to Send to an Input Binding

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#2563]
See https://stackoverflow.com/questions/74455728/streambridge-not-sending-acknowledgment-header/74478793#74478793

This is not the first time I have seen users being confused by this.

Perhaps the framework could reject such actions, at least in 4.0?

**Comment by olegz** [comment]
The problem is with SB you can send to non-existing binding at which point the new binding will be created. Further more, we are not enforcing `name-in/out-0` scheme. You can do `SB.send("foo", "blah")` and it will work since `foo` binding will be created. SO i can not look at binding name to determine if it is IN or OUT binding. However, it appears that in this case it is the existing binding and that could be checked.

**Comment by garyrussell** [comment]
RIght; a dynamically creating binding will always be an output binding; the issue here is if we resolve a channel that is actually a predefined input channel.

**Comment by Mhsh** [comment]
Hi @garyrussell I have posted one of my application scenario at https://stackoverflow.com/questions/78510903/using-stream-bridge-to-send-message-from-one-onsumer-to-another-consumer

**Comment by Mhsh** [comment]
Hello @garyrussell ,

In stackoverflow the question attached initially you mentioned 
"When using a KafkaTemplate instead it is, of course, going via Kafka; that's why you are seeing different behavior.

You need an output binding with inbound-stream as its destination."

I have same scenario described https://stackoverflow.com/questions/78510903/using-stream-bridge-to-send-message-from-one-consumer-to-another-consumer 

where I want to send message to another exchange within the same application.
