### ISSUE TITLE
Kafka Streams Binder: deserialization exception handling mechanism not invoked when routing configured based on event types

### ISSUE THREAD

**Issue by flemaitre** [spring-cloud/spring-cloud-stream#2613]
When routing is configured based on event types (*), the configured deserialization exception handler (**) is not invoked, but the deserialization exception is handled by the default StreamsUncaughtExceptionHandler handler.

(*) https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_event_type_based_routing_in_kafka_streams_applications
(**) https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_handling_deserialization_exceptions_in_the_binder

Kafka Streams Binder 3.2.6

**Comment by sobychacko** [comment]
@flemaitre Any chance you can create a very minimal sample application where we can reproduce this issue with some instructions to reproduce?

**Comment by flemaitre** [comment]
@sobychacko Please find two demo apps (one for the Producer and one for the Consumer) here: https://github.com/flemaitre/scs-issue-2613-sample-app

**Comment by sobychacko** [comment]
@flemaitre Thanks for the sample app. I looked into this area of the binder after observing your configuration. Here is the problem. When event type routing is enabled, we will use a byte[] Serde by default regardless of the value-serde you configure or the one the binder infers. Then, later on, if we have an event-type match, we will deserialize using the proper Serde. When using a byte serde, the deserialization works almost all the time, and no error is thrown; When later on you get the exception from the proper Serde, the issue is that it is now too late to hook into Kafka Stream's deserialization exception handling mechanism as we are now deep through the binder stack. The deserialization exception handling only works at the front end of the Kafka Streams stack, i.e, when the record is deserialized by Kafka Streams originally. 

To fix this, we can introduce a new flag in which you force the proper value serde at the outset to use by Kafka Streams rather than a byte[] Serde. There is a slight performance hit here, as we may unnecessarily deserialize all the incoming records using a complex Serde rather than a pass-through Serde implementation such as the `ByteSerde`. 

Let me know if it makes sense and then we can go ahead and try implementing this solution.

**Comment by flemaitre** [comment]
@sobychacko Thanks for the explanations. If I understand your proposal, the binder will offer the possibility to configure a specific value Serde, let's say the io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde for example, which will be used instead of the ByteSerde for the first deserialization step (the one performed by Kafka Streams), so that deserialization exceptions will be thrown earlier and managed by Kafka Streams.

Your solution is fine for me and the impact on the performance is acceptable (to be mentionned in the documentation later). Let me know when an implementation is available so that I can give it a try.

Thanks.

**Comment by sobychacko** [comment]
@flemaitre We addressed this issue through the commit referenced above on the main branch (`4.0.x`). Could you verify that this works for you? See the associated docs changes for more details. Once you confirm, we can back-port the changes to `3.2.x`.

**Comment by flemaitre** [comment]
@sobychacko I finally found time to test your fix. It works like a charm ! Thank you very much for your reactivity and the quality of your work.

**Comment by sobychacko** [comment]
Glad to hear that the fix worked for you. Thanks!
