### ISSUE TITLE
Cleanup deprecated and obsolete properties in StreamFunctionProperties

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#2674]

**Comment by panovst** [comment]
Hello!  
in this commit, StreamFunctionConfigurationProperties is auto-configured instead of StreamFunctionProperties. 
However, Stream Function Configuration Properties only works with the "bindings" block. How is "spring.cloud.streamfunction.definition"" being read from the application.yml file now?
