### ISSUE TITLE
Remove the requirement of colon for binder type inclusion

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#269]
As a developer, I'd like to replace the usage of colon from binder type inclusion (_ex :rabbit :topic, :redis:topic_) from stream definition. 

This is related to #217.

**Comment by ilayaperumalg** [comment]
The `binderType` is specified with `colon` only in the metadata files where the binder implementation class is specified in `spring.factories` file. May be some other place we want to investigate the use of `colon`?

**Comment by markfisher** [comment]
First of all, as this issue is only related to DSL syntax, it belongs with `spring-cloud-dataflow` not `spring-cloud-stream`.

That said, I don't quite understand what this issue is suggesting, but the syntax that I'm hoping we can agree upon (after the merging of https://github.com/spring-cloud/spring-cloud-dataflow/pull/368 - where the `topic:` and `queue:` prefixes are made obsolete) is:

```
[binderKey]:destination > ...
```

If nothing is provided before the colon, the default binder key would be used. The parser would simply pass that value along with other binder properties, so it would align with binder keys configured in the registered application being specified, as described here: http://docs.spring.io/spring-cloud-stream/docs/current-SNAPSHOT/reference/htmlsingle/#_multiple_binders_on_the_classpath

**Comment by mbogoevici** [comment]
I think that there was some confusion here (partly my fault) that conflated this with Kafka escaping (which is currently removed). @sabbyanandan, I think we can close this now.
