### ISSUE TITLE
Test binder seems to conflict with embedded kafka

### ISSUE THREAD

**Issue by kitkars** [spring-cloud/spring-cloud-stream#2694]
**_Steps to replicate:_**

- Create this simple application using spring initializer with below dependencies

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka-reactive</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-binder</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka-test</artifactId>
			<scope>test</scope>
		</dependency>
```

```
@SpringBootApplication
public class IssueReplicateApplication {

	public static void main(String[] args) {
		SpringApplication.run(IssueReplicateApplication.class, args);
	}

	@Bean
	public Consumer<Flux<String>> consumer(){
		return flux -> flux
				.doOnNext(System.out::println)
				.subscribe();
	}

	@Bean
	ApplicationRunner runner(KafkaTemplate<byte[], byte[]> template) {
		return args -> {
			Flux.interval(Duration.ofMillis(100))
				.take(10)
				.doOnNext(i -> template.send("topic1", ("foo" + i).getBytes())).subscribe();
		};
	}

}
```

- add these properties
```
spring.cloud.stream.bindings.consumer-in-0.group=foo
spring.cloud.stream.bindings.consumer-in-0.destination=topic1
spring.cloud.stream.kafka.binder.consumer-properties.auto.offset.reset=earliest
```

- Ensure that the application is working. We should be able to see "foo1, foo2.." etc
- Let's create integration test using embedded kafka. 

```
@SpringBootTest
@EmbeddedKafka(
		partitions = 1,
		bootstrapServersProperty = "spring.kafka.bootstrap-servers",
		topics = "topic1"
)
class IssueReplicateApplicationTests {

	@Autowired
	private KafkaTemplate<byte[], byte[]> template;

	@Test
	void contextLoads() throws InterruptedException {
		Flux.interval(Duration.ofMillis(100))
			.take(10)
			.doOnNext(i -> this.template.send("topic1", ("foo" + i).getBytes()))
			.subscribe();

		Thread.sleep(10_000);
	}

}
```

**_Expected:_**

- We should be able to see the "foo1, foo2.." etc

**_Actual:_**

- The consumer is not even created. We could not see consumer config getting printed. If I remove `spring-cloud-stream-test-binder` , then test works as expected.

**Comment by sobychacko** [comment]
@kitkars We suggest not adding the test-binder dependency if you are not using a message channel-based binder. Since you are using the reactive Kafka binder, the right solution is to remove the dependency. I can see an issue in which if an application needs both binders (regular and reactive) in the same application, this could introduce an issue. Could you please let me know why you're adding the test-binder dependency if you are only using the reactive binder?

**Comment by kitkars** [comment]
@sobychacko , we might want to do both unit and integration tests.
test-binder is good for simple unit tests where we need to test our application logic.  embedded kafka is good for integration tests. 
But if you think it is a known issue, then I could always use embedded kafka option to be safe. I assumed you could provide some work around.

**Comment by sobychacko** [comment]
@kitkars If your application is based on the reactive binder, then using the test binder is basically a no-op. You cannot use the test binder with an underlying reactive function since the test binder is based on message channels. 

Closing the issue, as removing the dependency and relying on embedded Kafka, is the right strategy. Please feel free to re-open if there is anything else you need us to do to revisit this problem. Thanks!
