### ISSUE TITLE
StreamBridge partition calculation mechanism does not update used partition count at runtime when using kafka broker

### ISSUE THREAD

**Issue by oliverfuehrertsystems** [spring-cloud/spring-cloud-stream#2706]
We are using StreamBridge to produce records against different topics using 'partition-key-expression' mechanism.
If we change the partition count within kafka broker we have to restart the application to force the application to uses new partition count for partition calculation.

When we use Spring KafkaTemplate instead of StreamBridge it is possible to configure partition count updates during runtime using parameter 'spring.kafka.producer.properties.metadata.max.age.ms'. The updated partition count will be available in application after specified time in that case.

We are using spring-cloud-stream 3.2.7.

**Comment by sobychacko** [comment]
@oliverfuehrertsystems Did you try it on the latest GA versions? `4.0.2` is the latest GA.

**Comment by oliverfuehrertsystems** [comment]
We will test with a newer spring-cloud version (and spring boot) soon, but after having a look into the current code I can see that the necessary method org.springframework.cloud.stream.binder.PartitionHandler#setPartitionCount (see  https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/PartitionHandler.java) is still not called anywhere in the code after initial binding.

**Comment by oliverfuehrertsystems** [comment]
Our producer properties are ok.

It's not so easy to reproduce. We used our loadgenerater software (as producer) to continuosly send  records in a loop to local kafka. We changed partion count in our kafka during that run and recognized that new partitions are never used until we restart our loadgenerator. 

If you look into the code you see that the used PartitionHandler stores the partitionCount in a member variable. This member variable is only updated during initialization phase and never called later during runtime.

Kafka libs may support an metatdata update mechanism (KafkaTemplate spring libraries use e.g. parameter 'spring.kafka.producer.properties.metadata.max.age.ms' for that) where a change of partition count for a topic is received. 

This mechanism should be also implemented within SCS and within that code the method PartitionHandler::setPartitionCount should be called.

**Comment by oliverfuehrertsystems** [comment]
I think about it, but the AbstractMessageChannel architecture is something I have to dive in deep ;)

**Comment by oliverfuehrer** [comment]
I created a fix implementing a new KafkaPartitionHandler (mostly a copy of existing PartitionHandler), which is called within KafkaMessageChannelBinder.ProducerConfigurationMessageHandler and gets an updated partitionCount from KafkaTemplate.

It was not able to extend the existing PartitionHandler to use a reference to internal KafkaTemplate, because of not allowed dependency from spring-cloud-stream-core to spring-cloud-stream-binder-kafka.

The current implementation does not satisfy me, but fixes the problem. I wrote a sample application which sends messages using 'partition-key-expression' repeatedly.

The test works as follows:
- Start the sample application and start message sending using http-request
- Observe messages with following command: kafka-console-consumer.sh --topic sampleTopic --bootstrap-server localhost:9092 --property print.value=false --property print.partition=true
- Chance partition count with following command: kafka-topics.sh --bootstrap-server localhost:9092 --topic sampleTopic --alter --partitions 10
- Observer messages again with same command (has to be restarted also)
-> Without my fix: new partitions will never be used
-> With my fix: new partitions will be uses after some seconds (see configuration of sample app)

**Comment by sobychacko** [comment]
@oliverfuehrer I don't see your implementation (`KafkaPartitionHandler`) in the patch you provided. Do you know if that is missing? Also, can you provide the above as a proper sample application?

**Comment by oliverfuehrer** [comment]
Sorry made a mistake. Created new patch with: spring-cloud-stream% git diff main issue_#2706 >> issue_#2706.patch
Should also contain a new sample application:
[issue_#2706.patch](https://github.com/spring-cloud/spring-cloud-stream/files/11356700/issue_.2706.patch)

**Comment by sobychacko** [comment]
Thanks! We will review your fix and see how we can incorporate this into the current partitioning strategies. Are you also thinking of sending a proper PR if the review goes through fine?

**Comment by oliverfuehrer** [comment]
I created a local git branch and could create a PR. The fix will solve our current problem, but I think a bigger refactoring would be necessary. Within my fix the existing PartitionHandler will still be called and my new KafkaPartitionHandler afterwards again, which is not a good solution.

**Comment by oliverfuehrer** [comment]
My latest fix (for a test) disabled the activation of my 'KafkaPartitionHandler'. I provide a new patch file - sorry for that.

**Comment by oliverfuehrertsystems** [comment]
Never did that before. Do I have to fork before?

**Comment by oliverfuehrer** [comment]
See https://github.com/spring-cloud/spring-cloud-stream/pull/2720
