### ISSUE TITLE
Extract Binding interface

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#330]
Refactor the Binder API, removing the `unbind` method and moving it to the Binding. Also, make `Binding` an interface with just the `unbind` methods and have the invokers of `Binder.unbind()` call it directly instead.

**Comment by markfisher** [comment]
Should we consider having `Binding` implement `Lifecycle`?... or do we want to expose only the *stop* part of the lifecycle and hide the rest within the `Binder` implementations?

**Comment by mbogoevici** [comment]
I'm not sure about it. I was rather thinking `Closeable`. The current implementation does implement Lifecycle, but IIRC it is not registered as a bean in the main context, so in the end it is the Binder implementation delegating.

**Comment by markfisher** [comment]
Sure, `Closeable` is a better fit since as you point out it's really a user-managed object rather than a "bean"... I also think I prefer `close` to `unbind` as a method name in this case. The one thing that I do not like about `Closeable` is that `close` has a *throws* declaration for `IOException`.

**Comment by mbogoevici** [comment]
Yeah, we can reconsider - I suppose that some binder implementations could end up throwing an `IOException` when closing. Can't think of a real use case right now though.
