### ISSUE TITLE
Support default properties for bindings

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#446]
Suggested solution: add `@Value("${spring.cloud.stream.rabbit.binder.default.autoBindDlq}")` on binding properties and add `additional-spring-configuration-metadata.json` for completion.

**Comment by ilayaperumalg** [comment]
This means we allow both the `default `properties to be specified along with the actual `binding` properties themselves (for instance having both `spring.cloud.stream.rabbit.binder.default.autoBindDlq` and `spring.cloud.stream.rabbit.bindings.<channelName>.producer.autoBindDlq`)?

Given we already have the default values defined for these producer/consumer properties at the `field` level, I would like to understand the rational behind supporting the default properties along with the binding properties (which could override the default ones). @mbogoevici

**Comment by mbogoevici** [comment]
>Given we already have the default values defined for these producer/consumer properties at the field level, I would like to understand the rational behind supporting the default properties along with the binding properties (which could override the default ones).

That pretty much describes the motivation. If we had multiple inputs or outputs, it'd be useful to specify different defaults than the ones that the field is initialized with globally (while retaining the ability to do per-binding configuration).

**Comment by ilayaperumalg** [comment]
Since the binder specific binding properties (for example `RabbitProducerProperties` and `RabbitConsumerProperties`) aren't `ConfigurationProperties` themselves and they are instantiated explicitly, having `@Value` won't resolve automatically since it requires BeanPostProcessor to kick in or we need to explicitly resolve the properties using PropertyPlaceholder support. 

This featured is deferred for now.

**Comment by tonny1983** [comment]
May I know any solutions to set the properties ( something like `spring.cloud.stream.rabbit.bindings.<channelName>.content-type`) with java code but yaml files, please? I faced the problem that the output destination is dynamic according to the business logic, and so that I cannot list all the potential destinations in the yaml file.

**Comment by mbogoevici** [comment]
We don't support this yet, but we intend to do so by 1.1.0.RELEASE.
