### ISSUE TITLE
Add support for AWS Kinesis

### ISSUE THREAD

**Issue by atdi** [spring-cloud/spring-cloud-stream#453]
As long kafka is not available as a managed service on AWS this will be nice to have.

**Comment by artembilan** [comment]
:+1: 
Fully relates to the https://github.com/spring-projects/spring-integration-aws/issues/22

**Comment by atdi** [comment]
Where this should be implemented: here or in spring-integration-aws? The starter definitely should be here.

**Comment by mbogoevici** [comment]
Hi @atdi,

Opening the issue here was the right thing to do :). In terms of where this will eventually live: we encourage the development of binders in separate repositories (e.g. https://github.com/spring-cloud/spring-cloud-stream-binder-redis and https://github.com/spring-cloud/spring-cloud-stream-binder-gemfire) for ease of management and decoupling their release cycle (at least until they become stable enough). Until we get started on it though, it's good to have the requirement in a visible place (also see https://github.com/spring-cloud/spring-cloud-stream/issues/135 for example).

What @artembilan meant was that our binders are based on SI components, so the development of the Kinesis binder will also entail creating the associated SI inbound/outbound adapters for Kinesis - just as we do with Kafka for instance. Thus, an entire range of associated Spring projects can benefit from the progress.

Thanks for opening the issue and keep watching this space (or feel free to contribute if you'd like to hack on it for a bit, we are always welcoming that!). 

Cheers,
Marius

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-starters#9
