### ISSUE TITLE
remove reference on not existing spring-cloud-starter-bus-redis

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-stream#454]
I am little confused about the fact that suddenly a widely used artifact "spring-cloud-starter-bus-redis" disappeared without announce. At least there shall be a migration doc and it must be completly removed from doc, e.g http://cloud.spring.io/spring-cloud-stream/ . There is no occurrence in https://repo.spring.io any more.

**Comment by cforce** [comment]
i also can't find spring-cloud-starter-stream-redis 1.0.0.RC1 in repo  https://repo.spring.io

**Comment by dsyer** [comment]
The BOM also still has a reference to spring-cloud-starter-stream-local (which hasn't existed for a while I think).

**Comment by mbogoevici** [comment]
Hi @cforce,

This is a mistake in our POMs and web page and we will have this corrected for GA. Sorry for the inconvenience. 

Generally speaking, we do not recommend using Redis as a binder transport for anything else but development and limited testing. However, its presence in the main project and the Getting Started guides has encouraged its usage beyond the original intent, which is why we have decided to make it a separate project and artifact.

The `1.0.0.RC1` documentation to be found at http://docs.spring.io/spring-cloud-stream/docs/1.0.0.RC1/reference/htmlsingle/index.html is not referencing Redis anymore.

We have corrected the entry page to recommend one of the binders provided with the project instead (i.e. Kafka). We have also corrected the dependencies POM to remove the erroneous references to `redis` and `local`.

To ease the transition, we have planned on releasing a `1.0.0.RC1` and a `1.0.0.RELEASE` version of the Redis binder, which has trailed for a few days. We will do this shortly. 

Thanks for pointing this out.

**Comment by mbogoevici** [comment]
As an additional update, `spring-cloud-stream-binder-redis` version `1.0.0.RC1` has been release in the milestone repository as well.

**Comment by cforce** [comment]
That only kafka any more is a valid production binder is no lucky announcement. Furthermore i only see kafka currently, or is there any other not released binding technology supported?
Can you also point out from the main page of spring-cloud-stream and spring-cloud-bus, what are the differences of these both projetcs and when to choose what . Especially the current and future usage of supporting features in spring cloud (like microservice2microservice communication and spring cloud configuration pushing).

**Comment by dsyer** [comment]
Kafka and Rabbit are both fully represented in the repos and in documentation, so I don't really understand your comment.

**Comment by mbogoevici** [comment]
Hi @cforce,
We are still pre-GA, so bear with us while we update the documentation and links.  We document and support both Rabbit and Kafka into production (see reference docs), and we'll include links to other know binder implementations (including Redis, which we do not recommend for production) on the main page, e.g. Redis or Gemfire.

Thanks for the suggestions. I guess we can close this specific issue for now or is it anything that we want to address?

**Comment by cforce** [comment]
Looking foward for your progress. Tx for support.

**Comment by chrisport** [comment]
@mbogoevici 
Could you quickly explain why Redis implementation is not supported/recommended for production?

**Comment by dsyer** [comment]
@chrisport, Redis can't honour any of the "normal" quality of service requirements for messaging when it is operated with more than one node (in any configuration we've seen). It's fine in development (or production if you can tolerate outages) with a single server.
