### ISSUE TITLE
Add a flag to disable topic creation

### ISSUE THREAD

**Issue by Arghanil** [spring-cloud/spring-cloud-stream#504]
`spring-cloud-stream-binder-kafka` creates a topic if it's not already there. It also overwrites the number of partition and replication factor of any existing topic if the config in the application differs from what the topic currently has. Deleting a topic has been a troublesome experience for us (using 0.8.2) as the topic gets marked for deletion, and kafka doesn't start up. Would be great if there is a flag that can be set to disable topic creation by any app in the kafka.

**Comment by vkueffel** [comment]
Is this available in some release version? I've been using RC2 and just realized it auto-recreates topics with reduced partitions and replication factor. It also seems to ignore spring.cloud.stream.kafka.binder.minPartitionCount. When I start my app on an existing topic with 10 partitions and this config:

spring.cloud.stream.kafka.binder.autoConfigureTopics=false
spring.cloud.stream.kafka.binder.minPartitionCount=10

it still seems to drop and recreate the topic with one partition in a single instance setup. It actually seems to give precedence to the instance count over minPartitionCount. When I add this:

spring.cloud.stream.instanceIndex=0
spring.cloud.stream.instanceCount=10

it actually creates 10 partitions, setting spring.cloud.stream.instanceCount=1 and restart the app sets it back to 1. This is really bad since it drops the topic and recreates it.

**Comment by mbogoevici** [comment]
Hi,

This is fixed post-RC2 and available only in the current snapshot build. I will be available in the GA release (later this week).

**Comment by mbogoevici** [comment]
The `minPartitionCount` issue is fixed here: https://github.com/spring-cloud/spring-cloud-stream/issues/495

**Comment by mbogoevici** [comment]
The fact that the topic gets re-created is problematic though. Will open a separate issue for it.

**Comment by vkueffel** [comment]
Ah, further testing reveals it's actually worse. Even if the topic settings are exactly what it they should be (because it was created by the app itself) it seems to recreate the topic regardless. Not 100% sure about that yet though.

**Comment by mbogoevici** [comment]
What broker version are you using?

**Comment by vkueffel** [comment]
Currently on 0.8.2.1.

**Comment by mbogoevici** [comment]
0.8.2.1 is supported, and we've tested this with the 0.9 brokers - still using the 0.8 client internally. We will upgrade to 0.9 pretty soon.

**Comment by vkueffel** [comment]
OK, last comment, I promise. ;-)

the snapshot documentation says the default for spring.cloud.stream.kafka.binder.autoConfigureTopics is "true". Is that the right thing to do? Having to actively turn off that the software modifies kafka topics rather than actively turn it on seems not right to me.

**Comment by mbogoevici** [comment]
For now we intend to keep it that way, but at a minimum we should avoid the reducing partition count and/or the replication factor - see https://github.com/spring-cloud/spring-cloud-stream/issues/509.
