### ISSUE TITLE
Rabbit binder: no support for stateful retry

### ISSUE THREAD

**Issue by srnm** [spring-cloud/spring-cloud-stream#534]
Hello,

The use-case is transactional consumption of messages via a listener that uses spring-data-jpa.

RabbitConsumerProperties.transacted is supported but no DLQ with stateful retry.

"Stateful retry is appropriate if your listener is using a transactional resource that needs to be rollback on an exception (e.g. a stateful connection to a back end server). JPA is the canonical example. The semantics of stateful retry mean that a listener exception is propagated to the container, so that it can force a rollback. " from
http://docs.spring.io/spring-amqp/docs/1.5.6.RELEASE/api/org/springframework/amqp/rabbit/config/StatefulRetryOperationsInterceptorFactoryBean.html

Thanks,

**Comment by srnm** [comment]
Also,

Setting a transaction manager disables the retry advice, which is hinted at in the amqp docs.

But the amqp docs are unclear about when/why to actually use
factory.setTransactionManager(platformTransactionManager)...

thanks

**Comment by garyrussell** [comment]
Stateful retry is not appropriate here because the retry state is not shared across application instances. If we used stateful retry, there is no guarantee that the redelivery will come back to the same instance. This causes two issues:

- the actual number of delivery attempts will be `maxAttempts <= n < (maxAttempts * instanceCount)`
- memory leakage because the instances that did not process the final (or successful) attempt will have no opportunity to clean up the retry state

To be perfectly honest, when rabbitmq changed from queuing rejections at the tail of the queue, to the head (several years ago, which was the correct move IMO), stateful retry in the context of RabbitMQ no longer provides any real value, just overhead.

>Setting a transaction manager disables the retry advice, which is hinted at in the spring-amqp docs.

I am not sure why you say that; can you point me to that hint?

Having a transaction manager is independent of the container's advice chain.

**Comment by srnm** [comment]
I've learnt a lot from the code in the project, but, from your reply, and from the statement in the javadoc about the need for stateful retry with JPA, linked above, I take away the understanding that spring-cloud-stream can not support listeners that use JPA?

I'd like to configure correct operation of a DLQ with message listeners that use JPA.
I'm finding it difficult because of the interactions between

- defaultRequeueRejected
- setTransactionManager
- setAdviceChain with stateless and stateful retry

on SimpleRabbitListenerContainerFactory.

As to transactionManager and retry advice, I should not have used the term "disabled".
But I did read a warning about how transactions and retry advice interact.
Of course, now I can't find it.

I was trying to figure out why bad messages were not ending up in the dlq.
Here's the code I ended up with after stepping through the code in the debugger and discovering that the advice chain was _not_ being called if the PlatformTransactionManager was set on the container factory:

```Java
        if (useDLQ) {
            RabbitTemplate errorTemplate = new RabbitTemplate(this.cf);
            // from javadoc for StatefulRetryOperationsInterceptorFactoryBean:
            // The semantics of stateful retry mean that a listener exception is propagated to the container, so that it can force a rollback.
            // ie, use with JPA transactions
            Interceptor retryInterceptor = RetryInterceptorBuilder.stateful()
                .maxAttempts(1)
                .recoverer(new RepublishMessageRecoverer(errorTemplate, dlqExchange().getName(), "#"))
                .build();

            factory.setAdviceChain(retryInterceptor);
        } else {
            // interferes with RetryInterceptor
            factory.setTransactionManager(platformTransactionManager);
        }

Thanks for your help sorting this out!

**Comment by mbogoevici** [comment]
@srnm 

Have included a new issue for supporting more interaction between the binders and the application's manager: https://github.com/spring-cloud/spring-cloud-stream/issues/536.

For now, though, if your listener is transactional, e.g..

```
@SpringBootApplication
@EnableBinding(Sink.class)
public class StreamRabbitJpaApplication {

	@Autowired
	private TransactionRepository transactionRepository;

	@Autowired
	private AuditRecordRepository auditRecordRepository;

	public static void main(String[] args) {
		SpringApplication.run(StreamRabbitJpaApplication.class, args);
	}

	@StreamListener(Sink.INPUT)
        @Transactional
	public void save(Transaction transaction) {
                // save always
		Transaction saved = transactionRepository.save(transaction);
		if (!transaction.getAccountNumber().contains("fail")) {
			AuditRecord record = new AuditRecord();
			record.setAccountNumber(transaction.getAccountNumber());
			record.setSavedTransactionId(saved.getId());
                        // save only on success 
			auditRecordRepository.save(record);
		}
		else {
			throw new IllegalStateException("Unacceptable transaction");
		}
	}
}
```
(I am using @StreamListener as this is spring-cloud-stream, but the invocation chain originates in a Rabbit listener).

Whenever the method throws an exception (rolling back the database transaction automatically) it will be retried (each time in a new transaction) and at the end propagated to the container/binder where depending on your settings it will be either:
- requeued if no DLQ nor retry is enabled and `requeueRejected` is set to `true` (default)
- forwarded to the dlq if `republishToDlq` is enabled on the binder
- dropped if neither requeing and DLQ republishing are set

There is no explicit requirement to use stateful retry for JPA, and generally speaking not in any case where the listener method can be retried without side effects (generally speaking a good idea, and definitely the case here, as the condition that triggers the failure is the one that causes the rollback). What the stateful retries offer you (and the documentation tries to say) is the additional ability to store state and resources between invocations which makes only sense in certain cases (such as JPA). Again, that is not a precondition, and as @garyrussell  says, it comes with issues of its own. 

To deepen the analysis, the limitation of the solution above is that it does not explicitly synchronize transactions and relies on exceptions triggering both rollback and nacking - which would work almost all the time, but may have subtle side effects - e.g. if a transaction is rolled back manually (probably something you will rarely see in user code). Since the nacking is essentially a compensating measure and there is no XA support, outside manual rollback it makes little difference whether the nack happens because of the DB transaction rollback or because of the exception that triggered the DB transaction rollback: a message that fails will be redelivered. 

In any case, we want to include deeper transaction support for 1.1 and that's why we want to address https://github.com/spring-cloud/spring-cloud-stream/issues/536. 

Let me know how if this works for you.

**Comment by garyrussell** [comment]
Ah, yes, I made a subtle change to my answer...

> stateful retry in the context of RabbitMQ no longer provides any real value,  ... unless an external transaction manager is provided.

When using stateless retry, with an external transaction manager, the retries are invoked within the transaction so it's true that when synchronizing with, say, a JPA transaction, by injecting a transaction manager, you need stateful retry so a new transaction is started for each delivery attempt.

However, this still suffers from the issues that I cited about shared state when there are multiple application instances.

Using `@Transactional` on the listener is very similar (from a commit timing perspective) to injecting the transaction manager into the container; the DB tx is committed when the listener exits and the rabbit message acked almost immediately thereafter. So in most cases, it's functionally the same, and has the added benefit that a new DB transaction is started for each delivery attempt.

**Comment by srnm** [comment]
From your replies, the following should work:

```Java
        SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory();
        factory.setMessageConverter(mc);
        factory.setConnectionFactory(cf);
        factory.setConcurrentConsumers(1);
        factory.setMaxConcurrentConsumers(1);
        factory.setDefaultRequeueRejected(false);
        factory.setChannelTransacted(true);
        factory.setTransactionManager(platformTransactionManager);

        // use a non-transactional template for the DLQ
        RabbitTemplate dlqTemplate = new RabbitTemplate(this.cf);
        // from javadoc for StatefulRetryOperationsInterceptorFactoryBean:
        // The semantics of stateful retry mean that a listener exception is propagated to the container, so that it can force a rollback.
        // ie, use with JPA transactions
        //
        // nb: using a stateful interceptor requires listeners on a single node
        // otherwise a message could be delivered to a different node and the previous delivery state lost...
        Interceptor retryInterceptor = RetryInterceptorBuilder.stateful()
            .maxAttempts(1)
            .recoverer(new RepublishMessageRecoverer(dlqTemplate, dlqExchange().getName(), "#"))
            .build();
        factory.setAdviceChain(retryInterceptor);
```

But the result is *infinite retries* if the listener throws (pulled from debug console)
javax.validation.ConstraintViolationException, for example.
Only when setTransactionManager is not set will bad messages get sent to the DLQ.

Using
```xml
<spring-amqp.version>1.5.6.RELEASE</spring-amqp.version>
```

Not sure if this is a doc bug, or an implementation bug?
It's likely you'll encounter this when testing #536.

Thanks

**Comment by garyrussell** [comment]
Bear in mind that the DB commit is performed after the retry recoverer has absorbed the exception (when retries are exhausted).

If that commit (the DB) fails then the Rabbit TX will be rolled back too.

Another reason for starting the DB transaction by annotating the listener instead of injecting a transaction manager so the DB transaction is within the scope of the retry rather than the other way around.

**Comment by srnm** [comment]
I think I understand now. You had to say it twice :)
=> Use @Transactional if possible. Set the platformTransactionManager if you want to enlist the rabbit listener because you are _not_ using @Transactional -- but there are problems with that approach.

My listeners _are_ using @Transactional *and* I was setting the platformTransactionManager -- so that might explain the infinite retry corner case where stateful retry advice was ignored.

This is all complected and subtle stuff.
The docs explain much but there are gaps.

I think a common use case is the desire to do less expensive multi-resource transactions, specifically Rabbit Listener + JPA. I am still unclear on how well spring-cloud-stream supports this use-case.
Specifically, the interaction between multiple nodes, consumer groups, partitioning, and stateless retries for the DLQ.

Thanks again...

**Comment by mbogoevici** [comment]
@srnm 

Thanks (again) for the interest in Spring Cloud Stream.

>I think a common use case is the desire to do less expensive multi-resource transactions, specifically Rabbit Listener + JPA. I am still unclear on how well spring-cloud-stream supports this use-case.
Specifically, the interaction between multiple nodes, consumer groups, partitioning, and stateless retries for the DLQ.

I would argue that stateless transactions are easier to reason around here, as stateless retries will ensure that a message is processed on a specific node, either resulting in a successful attempt or in DLQ redelivery. This is orthogonal to groups/partitioning.

**Comment by artembilan** [comment]
IMO Spring AMQP `SimpleMessageListenerContainer` should be reworked to get rid of `transactionManager` and just rely on the `TransactionInterceptor` as a part of the `adviceChain`.

If you agree with me I can fill the JIRA for SA-2.0.

You can do that already now and control yourself the order of `retry -> tx` or `tx -> retry` advices. And again: you don't need stateful there.

**Comment by garyrussell** [comment]
Makes sense to me; I was talking to @dsyer about this briefly last night - Dave - any thoughts?

**Comment by dsyer** [comment]
Yeah, the advice chain is a new feature (from the point of view of transactions in Spring Rabbit), so it wasn't available when we first wrote that code. Is it supported in Spring Rabbit directly, or only through Spring Integration? I would argue in any case that we need an opinionated API (Java or configuration) somewhere in the stack that knows how to do those two scenarios and gives them names that make sense to users (as a user I don't care about interceptors, I only care about the features, and the order). That could be in Spring Rabbit, or higher in the stack (like here, for example).

A comment on stateful/less retry with JPA is also probably appropriate. In general Hibernate (and so I would guess all JPA providers) certainly used to recommend heavily that once there is an exception that would cause a rollback you should discard the session (i.e. entity manager I guess), and proceed to rollback. That makes sense because it is stateful itself, and might contain data from the previous attempt if you continue with a stateless retry, and might lead to bad behaviour. Whether or not it does is probably highly dependent on the use case.

Gary's point about stateful retry being a memory leak is correct in spirit, but the default implementation of the `RetryContextCache` uses weak references, so you always get the memory back under GC pressure. As far as I know, that pattern is still used successfully in plenty of enterprises (including the original implementation in Spring Batch, which was from a global investment bank). `RetryContextCache` is also a strategy, so you could provide a global implementation if you needed to care about that. I never knew of anyone doing that in anger.

So what are the options, if you don't want to, or can't, use stateful retry? If there is a re-delivery count available from the broker, and the count is the only input into the retry policy, it would be cleaner to use that instead of trying to store state anywhere in the application. I'm pretty sure Rabbit didn't have that feature last time I looked, but it's possible that's changed. If not, you should at least be able to get an indication that a message was re-delivered. If you can, then you could adopt a simple policy of "retry once, if you detect a redelivery, and punt to the error channel if not".

P.S. it really shouldn't matter (much) if you use `@Transactional` listener inside a transactional listener container, unless you set the propagation to something weird (the existing transaction will just propargate). Maybe there's more of a story there, or maybe @srnm actually got confused and that wasn't contributing to his problems after all, or maybe he put in the wrong transaction manager or something.

**Comment by srnm** [comment]
@dsyer I certainly admit to confusion.
This is my first time implementing a rabbit listener and there are many facets to coordinate -- which is why I turned to spring-cloud-stream to see how it's done.

But since it is my first time -- I tried to keep things as simple as possible while working things out and doing some testing.

My experience shows that if you use @Transactional on the listener, set the platform transaction manager on the SimpleListenerContainerFactory, and set a stateless retry you should see infinite retries if the listener throws, as a result of a JPA exception for example. I didn't try to narrow down why...

**Comment by mbogoevici** [comment]
@srnm 

>But I use stateful retry advice for the DLQ. This still appears to be the "most correct" way to do a listener that uses JPA?

Can you explain why you think that, since all the answers in this thread have stated the contrary ?

**Comment by garyrussell** [comment]
Stateful retry (in this context) is only needed for JPA if you are using a PTM, if you are not using a PTM, the JPA transaction is bounded by the listener invocation - so stateless Vs. stateful is moot in that context).

>f there is a re-delivery count available from the broker, and the count is the only input into the retry policy, it would be cleaner to use that instead of trying to store state anywhere in the application. 

There is  no such counter, just a redelivered flag.

If you don't care about ordering, there are some tricks to implement retry in the broker itself, without using Spring Retry  - DLX/DLQ with a TTL (time to live) on the DLQ and configured such that the expired DLQ message is requeued back to the original queue and the cycle starts again. It gets a bit tricky because in order to avoid an infinite (delayed) loop, you have to examine the `x-death` header to see how many times around the loop it's been and give up after some number of attempts. It gets even more complex to the configure if you want an exponential (or variable) retry delay in the DLQ.

**Comment by srnm** [comment]
@mbogoevici @garyrussell 

Are you discounting dsyer's comment ?:
> A comment on stateful/less retry with JPA is also probably appropriate. In general Hibernate (and so I would guess all JPA providers) certainly used to recommend heavily that once there is an exception that would cause a rollback you should discard the session (i.e. entity manager I guess), and proceed to rollback. That makes sense because it is stateful itself, and might contain data from the previous attempt if you continue with a stateless retry, and might lead to bad behaviour. Whether or not it does is probably highly dependent on the use case.

Can someone verify that the currently supported ORMs no longer require stateful retry?

**Comment by garyrussell** [comment]
No; not discounting, just explaining that your use case doesn't need it.

>Whether or not it does is probably highly dependent on the use case.

As long as you __don't__ inject a `PlatformTransactionManager` and start the transaction __after__ the retry advice (e.g. with `@Transactional`) then you do not need stateful retry. The need for stateful retry __when__ using a `PTM` is solely because the retry advice catches and consumes the exception; the DB commit then fails, which also causes the rabbit TX to roll back even though it was "recovered" when retries were exhausted. When there's a PTM, we need each delivery attempt to throw the exception back to the container so a new DB TX will be started for the next delivery attempt.

**Comment by sabbyanandan** [comment]
@srnm: If you have any follow-up comments/thoughts, please reopen it with the details.
