### ISSUE TITLE
Make channel name configurable

### ISSUE THREAD

**Issue by vsrahul82** [spring-cloud/spring-cloud-stream#579]
For the following Source class

public interface MessageChannels {

	   @Output("activationMsgQueue")
	    MessageChannel save();
}

How can i make the channel name "activationMsgQueue" configurable? Should pick up the value from yaml file. 

Thanks in advance
-Rahul

**Comment by mbogoevici** [comment]
Hi Rahul,

Channel names are not configurable. You can use the `destination` property of the binding to poin them to a different destination (i.e. topic).

It's hard for me to see where that could be useful - as they are bean names and part of the configuration - e.g. they can be injected in other Spring Integration components, so I'm not sure what the dynamic naming would achieve. 

Can you rather describe your use case though?

**Comment by vsrahul82** [comment]
During code review i got a comment that the channel name looks hardcoded and so prefer it to be read from config file. That is why i raised the question.

**Comment by vsrahul82** [comment]
Please revert Marius.

**Comment by mbogoevici** [comment]
Hey @vsrahul82 , 

Sorry, I thought I'd posted the answer here, but apparently missed this.

In short: because channels are beans and they may be injected into other beans - e.g. Spring Integration endpoints, making their names arbitrarily modifiable at runtime would just make things complicated on the configuration end (and most likely impossible to manage, as beans in an application won't be able to reliably reference other beans). The same logic as for qualifiers applies in this case - in fact `@Input` and `@Output` are qualifiers as well. 

So this is not a feature that we intend to support.

**Comment by sabbyanandan** [comment]
This is not relevant anymore; closing this for now.
