### ISSUE TITLE
Documentation for @Bindings

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#644]
The javadocs are a bit thin and I can't see an example in the user guide anywhere.

**Comment by mbogoevici** [comment]
I am wondering if we shouldn't deprecate this completely, to be honest. `@Bindings` adds very little value, as:

- you can inject an input/output interface (e.g. `Source`) directly without the qualifier;
- you can't have multiple beans of an interface type as their channel names would overlap, so this is qualifying an already unique bean instance. Conversely, we can qualify what that means: - alternate/restricted views of the same channel set perhaps ? I feel that the added complexity brings little benefit;

This is an offshoot of an early day hypothesis, that you could have multiple `@EnableBinding` annotations for the same app so that you can chain modules together. I think that the current aggregation model is a better fit for that. wdyt @dsyer ?

**Comment by dsyer** [comment]
Sounds good to me. I won't miss it since I had no idea what it was for.

**Comment by mbogoevici** [comment]
Closing this in favour of deprecation.
