### ISSUE TITLE
Camden Release, Multiple stream listeners are not reflected in logs

### ISSUE THREAD

**Issue by ralston26** [spring-cloud/spring-cloud-stream#678]
I recently switched to Camden release , My application has 2 stream listeners which are listening to topics from 2 different channels (MultiSink), While using the 1.0.3 kafka starter version , I could see  2 different binders [kafka-binder-1] and [kafka-binder-2] in my logs correctly , but now I see only [afka-listener-1]  for all the messages consumed irrespective of the streamListener, Could'nt distinguish the listeners when i tried to send messages concurrently to both the channels.

**Comment by ilayaperumalg** [comment]
Hi,

`kafka-listener-1` is the Kafka consumer MessageListenerContainer's **executor** thread name suffix. In this case, this happens to be same name for both the binder versions since they assign the thread executor name with the same sequence. If the log message expands to display the full name of the executor, you would see the `beanName` in the prefix which could differentiate where the message comes from.

**Comment by ilayaperumalg** [comment]
I believe this can be closed based on the comment above. 

@ralston26 please feel free to re-open this if you have any more questions related to this or if you see any issue with having multiple stream listeners. Thanks!
