### ISSUE TITLE
Kafka should propagate all headers

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-stream#707]
Currently we have to pass the stream headers that we want to be propagated as environmental variables. With Sleuths baggage coming the very idea is to propagate whatever the user passes. 

It would be great if Kafka would propagate all headers without explicitly setting them.

**Comment by mbogoevici** [comment]
Thanks @marcingrzejszczak !

This ties a bit into the idea of standardizing common header management we've proposed in #628. Nonetheless - Sleuth should have a convention for custom headers - some prefix or another way of namespacing custom keys - otherwise it would be a high chance to interfering with standard headers.

**Comment by marcingrzejszczak** [comment]
Currently it does have a common prefix. It's "span"

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessageHeaders.java

For baggage it will be "baggage_"

**Comment by mbogoevici** [comment]
Duplicates #628
