### ISSUE TITLE
Spring boot 1.5.1 startup fails with object is not an instance of declaring class

### ISSUE THREAD

**Issue by runningonfumes** [spring-cloud/spring-cloud-stream#789]
I have a kafka producer but the configuration does not work in spring boot 1.5.1 while it does work in 1.4.4.

During startup I get the error : object is not an instance of declaring class

I made a very simple demo app that has the problem at startup.
[demo.zip](https://github.com/spring-cloud/spring-cloud-stream/files/762971/demo.zip)

Not sure this is a spring boot or a spring cloud stream issue

**Comment by mbogoevici** [comment]
@runningonfumes I suspect that this is caused by https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/88. We've currently fixed it in latest snapshot so I suggest you try using Initializr again (and  please check that the Spring Cloud Dependencies version is 'Dalston.BUILD-SNAPSHOT').

**Comment by runningonfumes** [comment]
Using Dalston.BUILD-SNAPSHOT does indeed solve the problem.

Thanks
