### ISSUE TITLE
Ability to use Kafka filtering and recordFilterStrategy

### ISSUE THREAD

**Issue by reda-alaoui** [spring-cloud/spring-cloud-stream#796]
Hello,
I am building an application which produces and consumes messages to/from the same kafka topic (shared with other applications).
Therefore, I want to be able to filter out messages produced by the application itself.
To do that with efficiency, I want to filter messages as soon as possible.

I think that `FilteringAcknowledgingMessageListenerAdapter` is the solution.
But to use it, I need to be able to pass a `RecordFilterStrategy` to `KafkaMessageDrivenChannelAdapter`.

Would it be ok to add a specific kafka property describing a `RecordFilterStrategy` class name?
If not, how can I do that?

**Comment by garyrussell** [comment]
Spring Integration does not currently support wrapping its internal listener in another adapter such as the filtering adapter.

You would have to use spring-kafka's `@KafkaListener` instead of `@StreamListener`. There, you can inject a `RecordFilterStrategy` into the `ConcurrentKafkaListenerContainerFactory`.

Feel free to open an issue at [spring-integration-kafka](https://github.com/spring-projects/spring-integration-kafka/issues) and we can look at adding the capability.

**Comment by artembilan** [comment]
The `` wraps into `FilteringAcknowledgingMessageListenerAdapter ` its listener since `2.0.1`: 

https://github.com/spring-projects/spring-integration-kafka/blob/master/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageDrivenChannelAdapter.java#L219

The question is how to get a gain of that `RecordFilterStrategy` in the Kafka Binder for the `KafkaMessageDrivenChannelAdapter`.

Am I right?

**Comment by mbogoevici** [comment]
That configuration seems to be tied to the retry functionality of the `KafkaMessageDrivenChannelAdapter `. Maybe it shouldn't be.

In any case, while we can allow the infrastructure of the Kafka binder to be more flexible, I wonder what about the benefits.  This seems to be a scenario where a Spring Integration Filter would be equally appropriate (and for that matter portable as well).

cc/ @artembilan @garyrussell

**Comment by artembilan** [comment]
> That configuration seems to be tied to the retry functionality of the KafkaMessageDrivenChannelAdapter. 

I don't think so. Look, the logic there is based on the:
```
boolean filterInRetry = this.filterInRetry && this.retryTemplate != null
					&& this.recordFilterStrategy != null;
```

But if you still have some doubts, please, open an appropriate issue in SI Kafka.

Yes, SI `filter` in the target SCSt application for the `INPUT` channel is good and really portable compromise.

**Comment by mbogoevici** [comment]
@artembilan What I meant was that in the `KafkaMessageDrivenChannelAdapter`, if `this.retryTemplate` is null (no retry configured) then `filterInRetry` will be `false` and  `FilteringAcknowledgingMessageListenerAdapter` will not be set. In any case, this is beyond the scope of the original issue.

**Comment by mbogoevici** [comment]
@artembilan My mistake - there's an else branch that I missed, so you're right.

In any case, my original observation remains: I think we should rather use a Filter in a SCSt solution.

**Comment by reda-alaoui** [comment]
Hello,
Thank you for your answers.
I want to continue to use Spring Cloud Stream and be able to filter before payload deserialization.
I do not know the other solutions (SCSt, S-I-Kafka, Spring Kafka).

1- Does SCSt provide filtering before payload deserialization?
2- Is there a way to tweak `KafkaBinderConfiguration.kafkaMessageChannelBinder()` from `spring-cloud-stream-binder-kafka` to add a `RecordFilterStrategy` to `kafkaMessageDrivenChannelAdapter`? If not how should I do it? Could we add a way to tweak it?
3- Finally can you give me more details about the simplest way to reach my goal?

I am prone to contribute with PRs if needed.

**Comment by artembilan** [comment]
1.  Spring Cloud Stream is fully based on Spring Integration. The `pring-cloud-stream-binder-kafka` is fully based on the Spring Kafka and Spring Integration for Kafka. So, you still continue to use Spring Cloud Stream but pull a bit Spring Integration API, principles and design techniques to your application. Finally the application would be what you and customer expect.

2. No, SCSt doesn't provide filtering. More over  Spring Kafka doesn't do that. Even if with `RecordFilterStrategy`, we already have deserialization from Kafka before processing records.

3. No, there is no now way to tweak `kafkaMessageChannelBinder` for the `RecordFilterStrategy`. What we suggest is like `filter` EI pattern implementation from Spring Integration: http://docs.spring.io/spring-integration/reference/html/messaging-routing-chapter.html#filter.
And no, I don't think that we will add that option, just because it must be a bean, no just simple property.

4. I think something like simplest solution can be like:
````java
@Filter(inputChannel = Processor.INPUT, outputChannel = "processRecord")
public boolean filterRecord(ConsumerRecord<?, ?> consumerRecord) {
    // filtering logic
}

@StreamListener("processRecord")
@SendTo(Processor.OUTPUT)
public Object processRecord(MyPojo data) {
   ....
}
````

5. We always welcome contribution, but you should be sure that you are familiar with all the API used by Spring Cloud Stream in particular Spring Integration. 
That reminds me a story like: how can you use JPA not knowing JDBC?..

**Comment by reda-alaoui** [comment]
Ok thank you.
If there is no way to filter before payload deserialization and after headers deserialization, then I will use the @Filter solution.

I was proposing to contribute following your eventual guidance ;)

**Comment by artembilan** [comment]
headers ???

Kafka doesn't have notion of message header.
What you see in SCSt is artificial solution based on convention. And finally everything becomes a Kafka message body. Therefore we can't have headers before payload anyway. Because we have to deserialize Kafka message fully and only after that we apply our algorithm to extract headers and payload separately.

**Comment by reda-alaoui** [comment]
I see.
My second idea was to be able to set kafka record id myself from the producer and filter on it. Maybe it is also a chimera ...

**Comment by artembilan** [comment]
That's fine. Spring Kafka populates the key to the headers like:
```
Map<String, Object> rawHeaders = kafkaMessageHeaders.getRawHeaders();
rawHeaders.put(KafkaHeaders.RECEIVED_MESSAGE_KEY, record.key());
rawHeaders.put(KafkaHeaders.RECEIVED_TOPIC, record.topic());
rawHeaders.put(KafkaHeaders.RECEIVED_PARTITION_ID, record.partition());
rawHeaders.put(KafkaHeaders.OFFSET, record.offset());

if (acknowledgment != null) {
	rawHeaders.put(KafkaHeaders.ACKNOWLEDGMENT, acknowledgment);
}
```
With many others as you see.

**Comment by reda-alaoui** [comment]
Ok thanks for the tips !
Closing this issue.

**Comment by ashankabiswas** [comment]
> headers ???
> 
> Kafka doesn't have notion of message header.
> What you see in SCSt is artificial solution based on convention. And finally everything becomes a Kafka message body. Therefore we can't have headers before payload anyway. Because we have to deserialize Kafka message fully and only after that we apply our algorithm to extract headers and payload separately.

@artembilan In that case, does it really make a difference if we filter the message in KafkaConfiguration class (@filter) or we consume the message and do Programmatic filtration in Listener class

**Comment by olegz** [comment]
@ashankabiswas  Please do not comment on closed issues especially with questions.. Please us [Stack Overflow channel](https://stackoverflow.com/tags/spring-cloud-stream).
