### ISSUE TITLE
How publish events to Kafka Topic without introducing Ouputchannel Java interface.

### ISSUE THREAD

**Issue by dvsridhar** [spring-cloud/spring-cloud-stream#821]
Hello,
This is not an issue but more of a Spring cloud stream kafka output channel capabilities question. We use spring cloud stream kafka module to publish and subscribe events between several microservices. To publish an event to a kafka topic the developer has to set up output channel configuration and also an output channel java interface. However, we have an utility service that dynamically needs to broadcast message to several dynamic topics. We can achieve using spring cloud stream but it requires a code change every time we need to deal new a topic. We are OK with introducing new output channel definition in our config server, but is there a way we can publish events without introducing the java interface definition.

**Comment by ilayaperumalg** [comment]
Hi,

If I understand your requirements correct, you need to use `BinderAwareChannelResolver` when resolving your outbound destination names (the kafka topic names here) so that the message channels are bound to the Kafka topic via kafka binder dynamically. The property `spring.cloud.stream.dynamicDestinations` can have a pre-defined list of destination names or can be empty (to have all the resolved destination names to be bound).

**Comment by ilayaperumalg** [comment]
Hi @dvsridhar,

You can also check out [this](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/dynamic-source) sample that uses dynamic destination resolution.

Closing this as `answered` and please feel free to re-open if you have any more questions related o this.
