### ISSUE TITLE
Disabling TestSupportBinderAutoConfiguration leads to exception related to mapping default binder

### ISSUE THREAD

**Issue by sakemal** [spring-cloud/spring-cloud-stream#827]
I disabled TestSupportBinderAutoConfiguration by adding

spring.autoconfigure.exclude= org.springframework.cloud.stream.test.binder.TestSupportBinderAutoConfiguration
in applicaiton.properties but it resulted in the error
"Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.IllegalStateException: A default binder has been requested, but there is more than one binder available: test,kafka, and no default binder has been set."

So even with disabling TestSupportBinderAutoConfiguration test binder is still getting initialized . Am I missing something ?

I am using 1.0.2.RELEASE of spring-cloud-stream-test-support

**Comment by ilayaperumalg** [comment]
Hi,

In `1.0.x` this behaviour is expected by design. If you try this on `1.1.x` or `1.2.x` branches, then the `TestSupportBinder` will **always** have the precedence when multiple binders are used (this will happen irrespective of the binder config you can specify via bindings properties). This is because the `BinderFactory` used in the `TestSupportBinderAutoConfiguration` which returns the `TestSupportBinder`. 

I'd like to understand why do you want to used `TestSupportBinder` along with some other binder in your tests. `TestSupportBinder` is intended for the tests related to testing the app alone and I believe it is not intended to be used along with the real binder.

**Comment by sakemal** [comment]
Hi,
Is this issue fixed in the latest release ?
@ilayaperumalg  I need it because I have some scenarios of test that requires me to contact another application, sharing same topics on the Kafka. So my test case requires kafka binder to send message to Kafka server.  
But for most of my other tests and contract tests I need TestSupportBinder only.

**Comment by mbogoevici** [comment]
@sakemal It will be fixed in the next release.

**Comment by mbogoevici** [comment]
You can try snapshot build in the mean time

**Comment by sakemal** [comment]
sure thanks
