### ISSUE TITLE
Improve compatibility with the Confluent Platform

### ISSUE THREAD

**Issue by wtfc63** [spring-cloud/spring-cloud-stream#850]
Currently, Spring Cloud Stream provides a dedicated client for Confluent's Schema Registry. But because the Avro serializer used by Confluent's Kafka REST Proxy encodes the Schema-Id into the message payload, messages sent by the REST Proxy are not compatible with SCS's _AvroSchemaRegistryClientMessageConverter_.

As decribed in [their mailing list](https://groups.google.com/d/msg/confluent-platform/A7B6uSnJa5k/zL5MfSA4DSMJ), Confluent's serializer perfaces the actual Avro message with the Id of the message's Schema in their Schema Registry. Therefore, the _MessageConverter_ would need to extract the Schema-Id before deserializing the actual payload in a way similar to their _[AbstractKafkaAvroDeserializer](https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java#L89)_:
```
      ByteBuffer buffer = getByteBuffer(payload);
      id = buffer.getInt();
      String subject = includeSchemaAndVersion ? getSubjectName(topic, isKey) : null;
      Schema schema = schemaRegistry.getBySubjectAndID(subject, id);
      int length = buffer.limit() - 1 - idSize;
```

While trying to get SCS to work with the Confluent Platform, we already implemented a _[ConfluentSchemaRegistryClientMessageConverter]( https://gist.github.com/wtfc63/924f48360a410f0b48a1ea18d51f8439)_, but an official implementation would be preferable of course.

**Comment by manuelpolacek** [comment]
Hey guys.
I checked the implementation for the ConfluentSchemaRegistryClientMessageConverter. But nothing is shown, that it is compatible in both directions. The serialization of a message is missing. Confluent products couldn't read messages from a topic written by this converter.

If i decide to work with confluent products, i would also would like to serialize my messages in the same way that a kafka-connect for example could read those messages as well.

Further Confluent product, like kafka-connect which uses the confluent kafka avro serializers, create schema subjects with suffixes like topic-value and topic-key, which makes sense if key should be avro serialized as well.

Regards,
Manuel

**Comment by viniciusccarvalho** [comment]
@manuelpolacek They are not compatible. The rationale behind supporting Confluent's Schema Registry was to use it as a mean to store the schemas, not to make SCSt apps compatible with Confluent.

We depend on things such as a contentType header to support multiple types of serialization. We may also depend on other headers, and this has been a design decision that we may require some opinionated view.

When you interface with a 3rd party system that follows a different approach is hard to be able to keep all the promises that your framework makes to users and keeping things compatible.

One way we may address this issue is to enable a flag to change how we serialize data when using the confluent schema registry client, but I'm not so sure on how much this could expose us to potential side effects of those messages not having some headers.

Regardless, this is currently scheduled to be a Future feature that we may revisit after 2.0 is out. There are some aspects of 2.0 when it comes to contentType handling that may facilitate this integration.

**Comment by manuelpolacek** [comment]
Thank you for your response.

Of course the compatibility of a framework and promises given to the user should be kept. I totally agree.
In my eyes it wouldn't have an effect to the framework if you allow supporting to communicate with other confluent products. It's more like a small enrichment if it can be used to interact with other applications.

I did a simple adaption of the given ConfluentSchemaRegistryClientMessageConverter and tested it with kafka/kafka-connect. I was able to read and write in both directions that kafka-connect could read and write those information as well.

If this will be a feature for the future i would like participate.

**Comment by viniciusccarvalho** [comment]
Thank you for your interest, we have this as a feature in the backlog, but just not a priority ATM.

One area of concern is that we also modify the payload to embed headers, and the first byte is reserved for the version of the headerMode. I'm not sure how would allowing reading from confluent's format could interfere there, unless you always use raw mode for headers.

Right now we are revisiting the entire serialization/contentType story inside the framework, we will be on a better position to support this once 2.0 gets to a stable release. Then we may be able to create a toggle feature for this.

Regards

**Comment by olegz** [comment]
Giving that this issue is a bit dated and the fact that schema registry moved to it's [own repo](https://github.com/spring-cloud/spring-cloud-schema-registry), I am closing it here. However it doesn't mean the issue os not valid, but perhaps it needs to be refreshed and resubmitted
