### ISSUE TITLE
AvroSchemaRegistryClientMessageConverter NPE

### ISSUE THREAD

**Issue by lwshuo** [spring-cloud/spring-cloud-stream#897]
Hi team,

I'm on 1.1.1 and still seeing https://github.com/spring-cloud/spring-cloud-stream/issues/694

I'm trying to use confluent schema registry. I'm using 
`@EnableSchemaRegistryClient` and I also have these beans registered:

 @Bean
  public MessageConverter userMessageConverter() {
    return new AvroSchemaMessageConverter(MimeType.valueOf("avro/bytes"));
  }

  @Bean
  ConfluentSchemaRegistryClient confluentSchemaRegistryClient(){
    return new ConfluentSchemaRegistryClient();
  }

  @Bean
  AvroSchemaRegistryClientMessageConverter avroSchemaRegistryClientMessageConverter(){
    return new AvroSchemaRegistryClientMessageConverter( confluentSchemaRegistryClient());
  }

Is there anything that I'm missing?

**Comment by lwshuo** [comment]
Can someone point me to examples of how to properly use `ConfluentSchemaRegistryClient ` ?

**Comment by olegz** [comment]
@lwshuo

NPE is definitely a bug on our end, and we're about to fix it. That said, the issue you are describing is due to miss-configuration on your end which results in NPE instead of a more informative message, so let me explain. . .
When using `@EnableSchemaRegistryClient` you are relying on auto-configuration which could and should work out of the box. The only variable (customization) you are trying to introduce is `ConfluentSchemaRegistryClient`, which you can simply do by declaring only one Bean (see below):
```java
@Bean
@Primary
ConfluentSchemaRegistryClient confluentSchemaRegistryClient() {
	return new ConfluentSchemaRegistryClient();
}
```
That is all you need to ensure that instead of `DefaultSchemaRegistryClient`. The `@Primary` _. . .Indicates that a bean should be given preference when multiple candidates. . ._
 But when you defining all those beans (up above) you are essentially attempting to override what's already provided via auto-config and when you do that you are missing some of the dependencies required by some of the beans and in this case it's a `CacheManager` that is missing from your instance of `AvroSchemaRegistryClientMessageConverter`.

Anyway, as I said, we do recognize that NPE is not a good exception to be seen by the client and will fix it, you also need to adjust your configuration.

Please let us know

**Comment by lwshuo** [comment]
@olegz  I tried what you said and it works now. Thank you so much!
