### ISSUE TITLE
Consumers not respect the application's health.

### ISSUE THREAD

**Issue by matheusalagia** [spring-cloud/spring-cloud-stream#960]
Spring-boot-actuator comes with a health check endpoint. When some of health indicators (database, disk, memory...) are set to DOWN the application global state is set to DOWN as well. It's very useful for monitoring, routing and resilience... especially in production environment. 
However spring-cloud-stream not respect the application state and continue to process (or trying) messages from broker. This behavior makes a "sick" instance consume messages that could be successfully processed by a healthy instance in the same consumer group.

The consumers should be shutting down when the application is in some kind of trouble. Don't?

Thank you!

**Comment by mbogoevici** [comment]
> However spring-cloud-stream not respect the application state and continue to process (or trying) messages from broker.
> The consumers should be shutting down when the application is in some kind of trouble. Don't?

I believe there's some confusion here with regards to the expected behaviour with respect to health indicators - what in the  health information reference manual ([1]) makes you think that an application should stop consuming messages in response to its overall health ? The health indicators are generally used by external systems to assess the state of the application. 

Thank you for the question, and the suggestion though - this is a possible future enhancement. Currently, it is possible for a user to monitor the state of specific health indicators and start/stop the contexts in response to that. 

[1] https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-health

**Comment by mbogoevici** [comment]
We will be providing external hooks to control the application, so it can be externally monitored - see #763 #963.
