### ISSUE TITLE
Batch offset commit provisioning

### ISSUE THREAD

**Issue by noorulhaq** [spring-cloud/spring-cloud-stream#981]
Is there any way in cloud stream to perform batch commit, as provided by akka-kafka-stream shown below.
```java
final DB db = new DB();
Consumer.committableSource(consumerSettings, Subscriptions.topics("topic1"))
  .mapAsync(1, msg ->
    db.update(msg.record().value()).thenApply(done -> msg.committableOffset()))
  .batch(20,
    first -> ConsumerMessage.emptyCommittableOffsetBatch().updated(first),
    (batch, elem) -> batch.updated(elem))
    .mapAsync(3, c -> c.commitJavadsl())
  .runWith(Sink.ignore(), materializer);
```

**Comment by mbogoevici** [comment]
@noorulhaq 
Let's continue the discussion in the Kafka binder repository, since this is a Kafka-specific question.

Currently the ack mode is Batch (see http://docs.spring.io/spring-kafka/reference/htmlsingle/#committing-offsets). Do you want to process a batch of messages at once? Please follow https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/70.

Other than that, can you open an issue in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka and provide more details?

**Comment by mbogoevici** [comment]
@noorulhaq closing this for now - feel free to open an issue in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka if you need an additional feature.
