### ISSUE TITLE
If the bound element is a `NamedComponent`, set `componentName`

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#983]
We do not assign a `componentName` to binder-created entities, which makes things hard to track sometimes. See #978 for details.

**Comment by viniciusccarvalho** [comment]
I started looking into this, @artembilan maybe you could help out here, I saw your comment on #978 , looking at the code, the channels that we create we don't set a component name indeed, but the code at `AbstractMessageChannel` that is called to output the name of the channels rely on either the componentName or the beanName. From what I could see, the beanName is always set. So I'm not following what could be the issue. 

The original issue seems to be unrelated to this problem, do we really need to set a componentName when the getFullName of the channel would return the beanName as well?

Cheers

**Comment by artembilan** [comment]
@viniciusccarvalho ,

I won't mind if things have been changed since there.
My comment was really about the logic I see in the code:
```
public String getFullChannelName() {
		if (this.fullChannelName == null) {
			String contextId = this.getApplicationContextId();
			String componentName = this.getComponentName();
			componentName = (StringUtils.hasText(contextId) ? contextId + "." : "") +
					(StringUtils.hasText(componentName) ? componentName : "unknown.channel.name");
			this.fullChannelName = componentName;
		}
		return this.fullChannelName;
	}
```
So, `unknown.channel.name` is there only if:
```
public String getComponentName() {
	return StringUtils.hasText(this.componentName) ? this.componentName : this.beanName;
}
```
returns null/empty string.

I'm confirming though that `((DirectChannel) this.testSink.input()).getFullChannelName()` for the `SinkBindingWithDefaultsTests` really returns the proper name now:
```
application:-1.input
```

Therefore, this issue might be fixed already somehow.

Another thought though, that the channel might be called too early, so, the `this.fullChannelName` is set to unexpected `unknown.channel.name`. And that may happen before the proper `setBeanName()` call via `BeanFactory`. One of those cases is implicit call to the `subscribe()`, which by the good reasons should go to the later phase of endpoints start up.
